/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Build progress
 */
@Schema(description = "Build progress")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T21:55:47.726988+02:00[Europe/Rome]")

public class BuildProgressDTO {
    @SerializedName("subscriptionCode")
    private String subscriptionCode = null;

    @SerializedName("buildCode")
    private String buildCode = null;

    @SerializedName("errorMessage")
    private String errorMessage = null;

    @SerializedName("numberOfTasks")
    private Integer numberOfTasks = null;

    @SerializedName("percentage")
    private Integer percentage = null;

    @SerializedName("buildStatus")
    private String buildStatus = null;

    @SerializedName("startedTasks")
    private List<BuildProgressStartedTaskDTO> startedTasks = null;

    public BuildProgressDTO subscriptionCode(String subscriptionCode) {
        this.subscriptionCode = subscriptionCode;
        return this;
    }

    /**
     * Code of the subscription
     *
     * @return subscriptionCode
     **/
    @Schema(description = "Code of the subscription")
    public String getSubscriptionCode() {
        return subscriptionCode;
    }

    public void setSubscriptionCode(String subscriptionCode) {
        this.subscriptionCode = subscriptionCode;
    }

    public BuildProgressDTO buildCode(String buildCode) {
        this.buildCode = buildCode;
        return this;
    }

    /**
     * Code of the build
     *
     * @return buildCode
     **/
    @Schema(description = "Code of the build")
    public String getBuildCode() {
        return buildCode;
    }

    public void setBuildCode(String buildCode) {
        this.buildCode = buildCode;
    }

    public BuildProgressDTO errorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
        return this;
    }

    /**
     * Human readable error message
     *
     * @return errorMessage
     **/
    @Schema(description = "Human readable error message")
    public String getErrorMessage() {
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    public BuildProgressDTO numberOfTasks(Integer numberOfTasks) {
        this.numberOfTasks = numberOfTasks;
        return this;
    }

    /**
     * Total number of tasks that will be executed
     *
     * @return numberOfTasks
     **/
    @Schema(description = "Total number of tasks that will be executed")
    public Integer getNumberOfTasks() {
        return numberOfTasks;
    }

    public void setNumberOfTasks(Integer numberOfTasks) {
        this.numberOfTasks = numberOfTasks;
    }

    public BuildProgressDTO percentage(Integer percentage) {
        this.percentage = percentage;
        return this;
    }

    /**
     * Progress percentage
     *
     * @return percentage
     **/
    @Schema(description = "Progress percentage")
    public Integer getPercentage() {
        return percentage;
    }

    public void setPercentage(Integer percentage) {
        this.percentage = percentage;
    }

    public BuildProgressDTO buildStatus(String buildStatus) {
        this.buildStatus = buildStatus;
        return this;
    }

    /**
     * Current status of the build , possible values are \&quot;BUILDING\&quot;,\&quot;SUCCESS\&quot;,\&quot;FAIL\&quot;,\&quot;SCHEDULED\&quot;,\&quot;DELETED\&quot; or \&quot;UNKNOWN\&quot;
     *
     * @return buildStatus
     **/
    @Schema(description = "Current status of the build , possible values are \"BUILDING\",\"SUCCESS\",\"FAIL\",\"SCHEDULED\",\"DELETED\" or \"UNKNOWN\"")
    public String getBuildStatus() {
        return buildStatus;
    }

    public void setBuildStatus(String buildStatus) {
        this.buildStatus = buildStatus;
    }

    public BuildProgressDTO startedTasks(List<BuildProgressStartedTaskDTO> startedTasks) {
        this.startedTasks = startedTasks;
        return this;
    }

    public BuildProgressDTO addStartedTasksItem(BuildProgressStartedTaskDTO startedTasksItem) {
        if (this.startedTasks == null) {
            this.startedTasks = new ArrayList<BuildProgressStartedTaskDTO>();
        }
        this.startedTasks.add(startedTasksItem);
        return this;
    }

    /**
     * List of started tasks of this progress
     *
     * @return startedTasks
     **/
    @Schema(description = "List of started tasks of this progress")
    public List<BuildProgressStartedTaskDTO> getStartedTasks() {
        return startedTasks;
    }

    public void setStartedTasks(List<BuildProgressStartedTaskDTO> startedTasks) {
        this.startedTasks = startedTasks;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BuildProgressDTO buildProgressDTO = (BuildProgressDTO) o;
        return Objects.equals(this.subscriptionCode, buildProgressDTO.subscriptionCode) && Objects.equals(this.buildCode, buildProgressDTO.buildCode) && Objects.equals(this.errorMessage, buildProgressDTO.errorMessage) && Objects.equals(this.numberOfTasks, buildProgressDTO.numberOfTasks) && Objects.equals(this.percentage, buildProgressDTO.percentage) && Objects.equals(this.buildStatus, buildProgressDTO.buildStatus) && Objects.equals(this.startedTasks, buildProgressDTO.startedTasks);
    }

    @Override
    public int hashCode() {
        return Objects.hash(subscriptionCode, buildCode, errorMessage, numberOfTasks, percentage, buildStatus, startedTasks);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class BuildProgressDTO {\n");

        sb.append("    subscriptionCode: ").append(toIndentedString(subscriptionCode)).append("\n");
        sb.append("    buildCode: ").append(toIndentedString(buildCode)).append("\n");
        sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
        sb.append("    numberOfTasks: ").append(toIndentedString(numberOfTasks)).append("\n");
        sb.append("    percentage: ").append(toIndentedString(percentage)).append("\n");
        sb.append("    buildStatus: ").append(toIndentedString(buildStatus)).append("\n");
        sb.append("    startedTasks: ").append(toIndentedString(startedTasks)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
