/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Details of a build
 */
@Schema(description = "Details of a build")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T21:55:47.726988+02:00[Europe/Rome]")

public class BuildDetailDTO {
    public BuildDetailDTO() {
    }

    @SerializedName("subscriptionCode")
    private String subscriptionCode = null;

    @SerializedName("applicationCode")
    private String applicationCode = null;

    @SerializedName("applicationDefinitionVersion")
    private String applicationDefinitionVersion = null;

    @SerializedName("branch")
    private String branch = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("code")
    private String code = null;

    @SerializedName("buildStartTimestamp")
    private OffsetDateTime buildStartTimestamp = null;

    @SerializedName("buildEndTimestamp")
    private OffsetDateTime buildEndTimestamp = null;

    @SerializedName("buildVersion")
    private String buildVersion = null;

    @SerializedName("createdBy")
    private String createdBy = null;

    @SerializedName("status")
    private String status = null;

    @SerializedName("isPreview")
    private Boolean isPreview = null;

    @SerializedName("hasSnapshot")
    private Boolean hasSnapshot = null;

    @SerializedName("deployed")
    private Boolean deployed = null;

    @SerializedName("properties")
    private List<PropertyDTO> properties = null;

    public BuildDetailDTO subscriptionCode(String subscriptionCode) {
        this.subscriptionCode = subscriptionCode;
        return this;
    }

    /**
     * Code of the subscription
     *
     * @return subscriptionCode
     **/
    @Schema(description = "Code of the subscription")
    public String getSubscriptionCode() {
        return subscriptionCode;
    }

    public void setSubscriptionCode(String subscriptionCode) {
        this.subscriptionCode = subscriptionCode;
    }

    public BuildDetailDTO applicationCode(String applicationCode) {
        this.applicationCode = applicationCode;
        return this;
    }

    /**
     * Application code
     *
     * @return applicationCode
     **/
    @Schema(description = "Application code")
    public String getApplicationCode() {
        return applicationCode;
    }

    public void setApplicationCode(String applicationCode) {
        this.applicationCode = applicationCode;
    }

    public BuildDetailDTO applicationDefinitionVersion(String applicationDefinitionVersion) {
        this.applicationDefinitionVersion = applicationDefinitionVersion;
        return this;
    }

    /**
     * Application definition version
     *
     * @return applicationDefinitionVersion
     **/
    @Schema(description = "Application definition version")
    public String getApplicationDefinitionVersion() {
        return applicationDefinitionVersion;
    }

    public void setApplicationDefinitionVersion(String applicationDefinitionVersion) {
        this.applicationDefinitionVersion = applicationDefinitionVersion;
    }

    public BuildDetailDTO branch(String branch) {
        this.branch = branch;
        return this;
    }

    /**
     * Branch name
     *
     * @return branch
     **/
    @Schema(description = "Branch name")
    public String getBranch() {
        return branch;
    }

    public void setBranch(String branch) {
        this.branch = branch;
    }

    public BuildDetailDTO name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Build name
     *
     * @return name
     **/
    @Schema(description = "Build name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BuildDetailDTO code(String code) {
        this.code = code;
        return this;
    }

    /**
     * Build code
     *
     * @return code
     **/
    @Schema(description = "Build code")
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public BuildDetailDTO buildStartTimestamp(OffsetDateTime buildStartTimestamp) {
        this.buildStartTimestamp = buildStartTimestamp;
        return this;
    }

    /**
     * Build start timestamp
     *
     * @return buildStartTimestamp
     **/
    @Schema(description = "Build start timestamp")
    public OffsetDateTime getBuildStartTimestamp() {
        return buildStartTimestamp;
    }

    public void setBuildStartTimestamp(OffsetDateTime buildStartTimestamp) {
        this.buildStartTimestamp = buildStartTimestamp;
    }

    public BuildDetailDTO buildEndTimestamp(OffsetDateTime buildEndTimestamp) {
        this.buildEndTimestamp = buildEndTimestamp;
        return this;
    }

    /**
     * Build end timestamp
     *
     * @return buildEndTimestamp
     **/
    @Schema(description = "Build end timestamp")
    public OffsetDateTime getBuildEndTimestamp() {
        return buildEndTimestamp;
    }

    public void setBuildEndTimestamp(OffsetDateTime buildEndTimestamp) {
        this.buildEndTimestamp = buildEndTimestamp;
    }

    public BuildDetailDTO buildVersion(String buildVersion) {
        this.buildVersion = buildVersion;
        return this;
    }

    /**
     * Build version
     *
     * @return buildVersion
     **/
    @Schema(description = "Build version")
    public String getBuildVersion() {
        return buildVersion;
    }

    public void setBuildVersion(String buildVersion) {
        this.buildVersion = buildVersion;
    }

    public BuildDetailDTO createdBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Initiator of the build
     *
     * @return createdBy
     **/
    @Schema(description = "Initiator of the build")
    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public BuildDetailDTO status(String status) {
        this.status = status;
        return this;
    }

    /**
     * Current status of the build , possible values are \&quot;BUILDING\&quot;,\&quot;SUCCESS\&quot;,\&quot;FAIL\&quot;,\&quot;SCHEDULED\&quot;,\&quot;DELETED\&quot; or \&quot;UNKNOWN\&quot;
     *
     * @return status
     **/
    @Schema(description = "Current status of the build , possible values are \"BUILDING\",\"SUCCESS\",\"FAIL\",\"SCHEDULED\",\"DELETED\" or \"UNKNOWN\"")
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public BuildDetailDTO isPreview(Boolean isPreview) {
        this.isPreview = isPreview;
        return this;
    }

    /**
     * Get isPreview
     *
     * @return isPreview
     **/
    @Schema(description = "")
    public Boolean isIsPreview() {
        return isPreview;
    }

    public void setIsPreview(Boolean isPreview) {
        this.isPreview = isPreview;
    }

    public BuildDetailDTO hasSnapshot(Boolean hasSnapshot) {
        this.hasSnapshot = hasSnapshot;
        return this;
    }

    /**
     * Build has snapshot associated
     *
     * @return hasSnapshot
     **/
    @Schema(description = "Build has snapshot associated")
    public Boolean isHasSnapshot() {
        return hasSnapshot;
    }

    public void setHasSnapshot(Boolean hasSnapshot) {
        this.hasSnapshot = hasSnapshot;
    }

    public BuildDetailDTO deployed(Boolean deployed) {
        this.deployed = deployed;
        return this;
    }

    /**
     * Build is deployed
     *
     * @return deployed
     **/
    @Schema(description = "Build is deployed")
    public Boolean isDeployed() {
        return deployed;
    }

    public void setDeployed(Boolean deployed) {
        this.deployed = deployed;
    }

    public BuildDetailDTO properties(List<PropertyDTO> properties) {
        this.properties = properties;
        return this;
    }

    public BuildDetailDTO addPropertiesItem(PropertyDTO propertiesItem) {
        if (this.properties == null) {
            this.properties = new ArrayList<PropertyDTO>();
        }
        this.properties.add(propertiesItem);
        return this;
    }

    /**
     * Properties that are used for this build
     *
     * @return properties
     **/
    @Schema(description = "Properties that are used for this build")
    public List<PropertyDTO> getProperties() {
        return properties;
    }

    public void setProperties(List<PropertyDTO> properties) {
        this.properties = properties;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BuildDetailDTO buildDetailDTO = (BuildDetailDTO) o;
        return Objects.equals(this.subscriptionCode, buildDetailDTO.subscriptionCode) && Objects.equals(this.applicationCode, buildDetailDTO.applicationCode) && Objects.equals(this.applicationDefinitionVersion, buildDetailDTO.applicationDefinitionVersion) && Objects.equals(this.branch, buildDetailDTO.branch) && Objects.equals(this.name, buildDetailDTO.name) && Objects.equals(this.code, buildDetailDTO.code) && Objects.equals(this.buildStartTimestamp, buildDetailDTO.buildStartTimestamp) && Objects.equals(this.buildEndTimestamp, buildDetailDTO.buildEndTimestamp) && Objects.equals(this.buildVersion, buildDetailDTO.buildVersion) && Objects.equals(this.createdBy, buildDetailDTO.createdBy) && Objects.equals(this.status, buildDetailDTO.status) && Objects.equals(this.isPreview, buildDetailDTO.isPreview) && Objects.equals(this.hasSnapshot, buildDetailDTO.hasSnapshot) && Objects.equals(this.deployed, buildDetailDTO.deployed) && Objects.equals(this.properties, buildDetailDTO.properties);
    }

    @Override
    public int hashCode() {
        return Objects.hash(subscriptionCode, applicationCode, applicationDefinitionVersion, branch, name, code, buildStartTimestamp, buildEndTimestamp, buildVersion, createdBy, status, isPreview, hasSnapshot, deployed, properties);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class BuildDetailDTO {\n");

        sb.append("    subscriptionCode: ").append(toIndentedString(subscriptionCode)).append("\n");
        sb.append("    applicationCode: ").append(toIndentedString(applicationCode)).append("\n");
        sb.append("    applicationDefinitionVersion: ").append(toIndentedString(applicationDefinitionVersion)).append("\n");
        sb.append("    branch: ").append(toIndentedString(branch)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    code: ").append(toIndentedString(code)).append("\n");
        sb.append("    buildStartTimestamp: ").append(toIndentedString(buildStartTimestamp)).append("\n");
        sb.append("    buildEndTimestamp: ").append(toIndentedString(buildEndTimestamp)).append("\n");
        sb.append("    buildVersion: ").append(toIndentedString(buildVersion)).append("\n");
        sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    isPreview: ").append(toIndentedString(isPreview)).append("\n");
        sb.append("    hasSnapshot: ").append(toIndentedString(hasSnapshot)).append("\n");
        sb.append("    deployed: ").append(toIndentedString(deployed)).append("\n");
        sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
