/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CachingDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class CachingDTO {
  @SerializedName("code")
  private String code = null;

  @SerializedName("defaultExpire")
  private Integer defaultExpire = null;

  @SerializedName("maxExpire")
  private Integer maxExpire = null;

  @SerializedName("paths")
  private String paths = null;

  @SerializedName("enabled")
  private Boolean enabled = null;

  public CachingDTO code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Code of the caching configuration
   * @return code
  **/
  @Schema(description = "Code of the caching configuration")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public CachingDTO defaultExpire(Integer defaultExpire) {
    this.defaultExpire = defaultExpire;
    return this;
  }

   /**
   * Default expire time in seconds
   * @return defaultExpire
  **/
  @Schema(description = "Default expire time in seconds")
  public Integer getDefaultExpire() {
    return defaultExpire;
  }

  public void setDefaultExpire(Integer defaultExpire) {
    this.defaultExpire = defaultExpire;
  }

  public CachingDTO maxExpire(Integer maxExpire) {
    this.maxExpire = maxExpire;
    return this;
  }

   /**
   * Maximum expire time in seconds
   * @return maxExpire
  **/
  @Schema(description = "Maximum expire time in seconds")
  public Integer getMaxExpire() {
    return maxExpire;
  }

  public void setMaxExpire(Integer maxExpire) {
    this.maxExpire = maxExpire;
  }

  public CachingDTO paths(String paths) {
    this.paths = paths;
    return this;
  }

   /**
   * Comma separated list of paths that will be cached
   * @return paths
  **/
  @Schema(description = "Comma separated list of paths that will be cached")
  public String getPaths() {
    return paths;
  }

  public void setPaths(String paths) {
    this.paths = paths;
  }

  public CachingDTO enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Is caching enabled
   * @return enabled
  **/
  @Schema(description = "Is caching enabled")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CachingDTO cachingDTO = (CachingDTO) o;
    return Objects.equals(this.code, cachingDTO.code) &&
        Objects.equals(this.defaultExpire, cachingDTO.defaultExpire) &&
        Objects.equals(this.maxExpire, cachingDTO.maxExpire) &&
        Objects.equals(this.paths, cachingDTO.paths) &&
        Objects.equals(this.enabled, cachingDTO.enabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, defaultExpire, maxExpire, paths, enabled);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CachingDTO {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    defaultExpire: ").append(toIndentedString(defaultExpire)).append("\n");
    sb.append("    maxExpire: ").append(toIndentedString(maxExpire)).append("\n");
    sb.append("    paths: ").append(toIndentedString(paths)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
