/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DTO that contains data for SSL certificate creation
 */
@Schema(description = "DTO that contains data for SSL certificate creation")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class CreateSslCertificateDTO {
  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("certificate")
  private String certificate = null;

  @SerializedName("certificateKey")
  private String certificateKey = null;

  @SerializedName("caCertificate")
  private String caCertificate = null;

  public CreateSslCertificateDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * SSL certificate name
   * @return name
  **/
  @Schema(required = true, description = "SSL certificate name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CreateSslCertificateDTO description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Certificate description
   * @return description
  **/
  @Schema(description = "Certificate description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CreateSslCertificateDTO certificate(String certificate) {
    this.certificate = certificate;
    return this;
  }

   /**
   * Certificate in PEM format including the begin and end markers
   * @return certificate
  **/
  @Schema(required = true, description = "Certificate in PEM format including the begin and end markers")
  public String getCertificate() {
    return certificate;
  }

  public void setCertificate(String certificate) {
    this.certificate = certificate;
  }

  public CreateSslCertificateDTO certificateKey(String certificateKey) {
    this.certificateKey = certificateKey;
    return this;
  }

   /**
   * Matching private key for the certificate in PEM format including the begin and end markers
   * @return certificateKey
  **/
  @Schema(required = true, description = "Matching private key for the certificate in PEM format including the begin and end markers")
  public String getCertificateKey() {
    return certificateKey;
  }

  public void setCertificateKey(String certificateKey) {
    this.certificateKey = certificateKey;
  }

  public CreateSslCertificateDTO caCertificate(String caCertificate) {
    this.caCertificate = caCertificate;
    return this;
  }

   /**
   * Root certificate in PEM format including the begin and end markers
   * @return caCertificate
  **/
  @Schema(description = "Root certificate in PEM format including the begin and end markers")
  public String getCaCertificate() {
    return caCertificate;
  }

  public void setCaCertificate(String caCertificate) {
    this.caCertificate = caCertificate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateSslCertificateDTO createSslCertificateDTO = (CreateSslCertificateDTO) o;
    return Objects.equals(this.name, createSslCertificateDTO.name) &&
        Objects.equals(this.description, createSslCertificateDTO.description) &&
        Objects.equals(this.certificate, createSslCertificateDTO.certificate) &&
        Objects.equals(this.certificateKey, createSslCertificateDTO.certificateKey) &&
        Objects.equals(this.caCertificate, createSslCertificateDTO.caCertificate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, certificate, certificateKey, caCertificate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateSslCertificateDTO {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    certificate: ").append(toIndentedString(certificate)).append("\n");
    sb.append("    certificateKey: ").append(toIndentedString(certificateKey)).append("\n");
    sb.append("    caCertificate: ").append(toIndentedString(caCertificate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
