/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Create build response
 */
@Schema(description = "Create build response")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T21:55:47.726988+02:00[Europe/Rome]")

public class CreateBuildResponseDTO {
    public CreateBuildResponseDTO() {
    }

    @SerializedName("subscriptionCode")
    private String subscriptionCode = null;

    @SerializedName("code")
    private String code = null;

    public CreateBuildResponseDTO subscriptionCode(String subscriptionCode) {
        this.subscriptionCode = subscriptionCode;
        return this;
    }

    /**
     * Code of the subscription
     *
     * @return subscriptionCode
     **/
    @Schema(description = "Code of the subscription")
    public String getSubscriptionCode() {
        return subscriptionCode;
    }

    public void setSubscriptionCode(String subscriptionCode) {
        this.subscriptionCode = subscriptionCode;
    }

    public CreateBuildResponseDTO code(String code) {
        this.code = code;
        return this;
    }

    /**
     * Build code
     *
     * @return code
     **/
    @Schema(required = true, description = "Build code")
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateBuildResponseDTO createBuildResponseDTO = (CreateBuildResponseDTO) o;
        return Objects.equals(this.subscriptionCode, createBuildResponseDTO.subscriptionCode) && Objects.equals(this.code, createBuildResponseDTO.code);
    }

    @Override
    public int hashCode() {
        return Objects.hash(subscriptionCode, code);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreateBuildResponseDTO {\n");

        sb.append("    subscriptionCode: ").append(toIndentedString(subscriptionCode)).append("\n");
        sb.append("    code: ").append(toIndentedString(code)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
