/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Entity to be used to make decision on a green deployment
 */
@Schema(description = "Entity to be used to make decision on a green deployment")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T21:55:47.726988+02:00[Europe/Rome]")

public class CreateDeploymentDecisionRequestDTO {
    @SerializedName("reason")
    private String reason = null;

    @SerializedName("decision")
    private DeploymentDecision decision = null;

    public CreateDeploymentDecisionRequestDTO reason(String reason) {
        this.reason = reason;
        return this;
    }

    /**
     * reason for deployment decision
     *
     * @return reason
     **/
    @Schema(description = "reason for deployment decision")
    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public CreateDeploymentDecisionRequestDTO decision(DeploymentDecision decision) {
        this.decision = decision;
        return this;
    }

    /**
     * Get decision
     *
     * @return decision
     **/
    @Schema(description = "")
    public DeploymentDecision getDecision() {
        return decision;
    }

    public void setDecision(DeploymentDecision decision) {
        this.decision = decision;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateDeploymentDecisionRequestDTO createDeploymentDecisionRequestDTO = (CreateDeploymentDecisionRequestDTO) o;
        return Objects.equals(this.reason, createDeploymentDecisionRequestDTO.reason) && Objects.equals(this.decision, createDeploymentDecisionRequestDTO.decision);
    }

    @Override
    public int hashCode() {
        return Objects.hash(reason, decision);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreateDeploymentDecisionRequestDTO {\n");

        sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
        sb.append("    decision: ").append(toIndentedString(decision)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
