/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Deployment decision response
 */
@Schema(description = "Deployment decision response")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T21:55:47.726988+02:00[Europe/Rome]")

public class CreateDeploymentDecisionResponseDTO {
    @SerializedName("newDeploymentCode")
    private String newDeploymentCode = null;

    @SerializedName("decision")
    private DeploymentDecision decision = null;

    @SerializedName("decison")
    private DeploymentDecision decison = null;

    public CreateDeploymentDecisionResponseDTO newDeploymentCode(String newDeploymentCode) {
        this.newDeploymentCode = newDeploymentCode;
        return this;
    }

    /**
     * Code of the new deployment, will have a value only when the decision is not REJECT.
     *
     * @return newDeploymentCode
     **/
    @Schema(description = "Code of the new deployment, will have a value only when the decision is not REJECT.")
    public String getNewDeploymentCode() {
        return newDeploymentCode;
    }

    public void setNewDeploymentCode(String newDeploymentCode) {
        this.newDeploymentCode = newDeploymentCode;
    }

    public CreateDeploymentDecisionResponseDTO decision(DeploymentDecision decision) {
        this.decision = decision;
        return this;
    }

    /**
     * Get decision
     *
     * @return decision
     **/
    @Schema(description = "")
    public DeploymentDecision getDecision() {
        return decision;
    }

    public void setDecision(DeploymentDecision decision) {
        this.decision = decision;
    }

    public CreateDeploymentDecisionResponseDTO decison(DeploymentDecision decison) {
        this.decison = decison;
        return this;
    }

    /**
     * Get decison
     *
     * @return decison
     **/
    @Schema(description = "")
    public DeploymentDecision getDecison() {
        return decison;
    }

    public void setDecison(DeploymentDecision decison) {
        this.decison = decison;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateDeploymentDecisionResponseDTO createDeploymentDecisionResponseDTO = (CreateDeploymentDecisionResponseDTO) o;
        return Objects.equals(this.newDeploymentCode, createDeploymentDecisionResponseDTO.newDeploymentCode) && Objects.equals(this.decision, createDeploymentDecisionResponseDTO.decision) && Objects.equals(this.decison, createDeploymentDecisionResponseDTO.decison);
    }

    @Override
    public int hashCode() {
        return Objects.hash(newDeploymentCode, decision, decison);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreateDeploymentDecisionResponseDTO {\n");

        sb.append("    newDeploymentCode: ").append(toIndentedString(newDeploymentCode)).append("\n");
        sb.append("    decision: ").append(toIndentedString(decision)).append("\n");
        sb.append("    decison: ").append(toIndentedString(decison)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
