/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Create datarestore request
 */
@Schema(description = "Create datarestore request")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T21:55:47.726988+02:00[Europe/Rome]")

public class CreateDatarestoreRequestDTO {
    @SerializedName("databackupCode")
    private String databackupCode = null;

    @SerializedName("sourceEnvironmentCode")
    private String sourceEnvironmentCode = null;

    public CreateDatarestoreRequestDTO databackupCode(String databackupCode) {
        this.databackupCode = databackupCode;
        return this;
    }

    /**
     * Databackup code
     *
     * @return databackupCode
     **/
    @Schema(description = "Databackup code")
    public String getDatabackupCode() {
        return databackupCode;
    }

    public void setDatabackupCode(String databackupCode) {
        this.databackupCode = databackupCode;
    }

    public CreateDatarestoreRequestDTO sourceEnvironmentCode(String sourceEnvironmentCode) {
        this.sourceEnvironmentCode = sourceEnvironmentCode;
        return this;
    }

    /**
     * Source environment (where the databackup was created)
     *
     * @return sourceEnvironmentCode
     **/
    @Schema(description = "Source environment (where the databackup was created)")
    public String getSourceEnvironmentCode() {
        return sourceEnvironmentCode;
    }

    public void setSourceEnvironmentCode(String sourceEnvironmentCode) {
        this.sourceEnvironmentCode = sourceEnvironmentCode;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateDatarestoreRequestDTO createDatarestoreRequestDTO = (CreateDatarestoreRequestDTO) o;
        return Objects.equals(this.databackupCode, createDatarestoreRequestDTO.databackupCode) && Objects.equals(this.sourceEnvironmentCode, createDatarestoreRequestDTO.sourceEnvironmentCode);
    }

    @Override
    public int hashCode() {
        return Objects.hash(databackupCode, sourceEnvironmentCode);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreateDatarestoreRequestDTO {\n");

        sb.append("    databackupCode: ").append(toIndentedString(databackupCode)).append("\n");
        sb.append("    sourceEnvironmentCode: ").append(toIndentedString(sourceEnvironmentCode)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
