/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.cx.commercecloud.management.openapi.model.DatabackupContent;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Create Databackup request
 */
@Schema(description = "Create Databackup request")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class CreateDatabackupRequestDTO {
  @SerializedName("description")
  private String description = null;

  @SerializedName("databackupContent")
  private DatabackupContent databackupContent = null;

  @SerializedName("databackupType")
  private String databackupType = null;

  public CreateDatabackupRequestDTO description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description
   * @return description
  **/
  @Schema(description = "Description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CreateDatabackupRequestDTO databackupContent(DatabackupContent databackupContent) {
    this.databackupContent = databackupContent;
    return this;
  }

   /**
   * Get databackupContent
   * @return databackupContent
  **/
  @Schema(description = "")
  public DatabackupContent getDatabackupContent() {
    return databackupContent;
  }

  public void setDatabackupContent(DatabackupContent databackupContent) {
    this.databackupContent = databackupContent;
  }

  public CreateDatabackupRequestDTO databackupType(String databackupType) {
    this.databackupType = databackupType;
    return this;
  }

   /**
   * Two possible values - QUICK, STANDARD
   * @return databackupType
  **/
  @Schema(description = "Two possible values - QUICK, STANDARD")
  public String getDatabackupType() {
    return databackupType;
  }

  public void setDatabackupType(String databackupType) {
    this.databackupType = databackupType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateDatabackupRequestDTO createDatabackupRequestDTO = (CreateDatabackupRequestDTO) o;
    return Objects.equals(this.description, createDatabackupRequestDTO.description) &&
        Objects.equals(this.databackupContent, createDatabackupRequestDTO.databackupContent) &&
        Objects.equals(this.databackupType, createDatabackupRequestDTO.databackupType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, databackupContent, databackupType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateDatabackupRequestDTO {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    databackupContent: ").append(toIndentedString(databackupContent)).append("\n");
    sb.append("    databackupType: ").append(toIndentedString(databackupType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
