/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Create datarestore response
 */
@Schema(description = "Create datarestore response")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T21:55:47.726988+02:00[Europe/Rome]")

public class CreateDatarestoreResponseDTO {
    @SerializedName("subscriptionCode")
    private String subscriptionCode = null;

    @SerializedName("environmentCode")
    private String environmentCode = null;

    @SerializedName("datarestoreCode")
    private String datarestoreCode = null;

    public CreateDatarestoreResponseDTO subscriptionCode(String subscriptionCode) {
        this.subscriptionCode = subscriptionCode;
        return this;
    }

    /**
     * Code of the subscription
     *
     * @return subscriptionCode
     **/
    @Schema(description = "Code of the subscription")
    public String getSubscriptionCode() {
        return subscriptionCode;
    }

    public void setSubscriptionCode(String subscriptionCode) {
        this.subscriptionCode = subscriptionCode;
    }

    public CreateDatarestoreResponseDTO environmentCode(String environmentCode) {
        this.environmentCode = environmentCode;
        return this;
    }

    /**
     * Code of the environment
     *
     * @return environmentCode
     **/
    @Schema(description = "Code of the environment")
    public String getEnvironmentCode() {
        return environmentCode;
    }

    public void setEnvironmentCode(String environmentCode) {
        this.environmentCode = environmentCode;
    }

    public CreateDatarestoreResponseDTO datarestoreCode(String datarestoreCode) {
        this.datarestoreCode = datarestoreCode;
        return this;
    }

    /**
     * Datarestore code
     *
     * @return datarestoreCode
     **/
    @Schema(required = true, description = "Datarestore code")
    public String getDatarestoreCode() {
        return datarestoreCode;
    }

    public void setDatarestoreCode(String datarestoreCode) {
        this.datarestoreCode = datarestoreCode;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateDatarestoreResponseDTO createDatarestoreResponseDTO = (CreateDatarestoreResponseDTO) o;
        return Objects.equals(this.subscriptionCode, createDatarestoreResponseDTO.subscriptionCode) && Objects.equals(this.environmentCode, createDatarestoreResponseDTO.environmentCode) && Objects.equals(this.datarestoreCode, createDatarestoreResponseDTO.datarestoreCode);
    }

    @Override
    public int hashCode() {
        return Objects.hash(subscriptionCode, environmentCode, datarestoreCode);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreateDatarestoreResponseDTO {\n");

        sb.append("    subscriptionCode: ").append(toIndentedString(subscriptionCode)).append("\n");
        sb.append("    environmentCode: ").append(toIndentedString(environmentCode)).append("\n");
        sb.append("    datarestoreCode: ").append(toIndentedString(datarestoreCode)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
