/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Entity to be used to start new builds
 */
@Schema(description = "Entity to be used to start new builds")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T21:55:47.726988+02:00[Europe/Rome]")

public class CreateBuildRequestDTO {
    public CreateBuildRequestDTO() {
    }

    @SerializedName("applicationCode")
    private String applicationCode = null;

    @SerializedName("branch")
    private String branch = null;

    @SerializedName("name")
    private String name = null;

    public CreateBuildRequestDTO applicationCode(String applicationCode) {
        this.applicationCode = applicationCode;
        return this;
    }

    /**
     * Code of the application
     *
     * @return applicationCode
     **/
    @Schema(description = "Code of the application")
    public String getApplicationCode() {
        return applicationCode;
    }

    public void setApplicationCode(String applicationCode) {
        this.applicationCode = applicationCode;
    }

    public CreateBuildRequestDTO branch(String branch) {
        this.branch = branch;
        return this;
    }

    /**
     * Branch name of the application
     *
     * @return branch
     **/
    @Schema(required = true, description = "Branch name of the application")
    public String getBranch() {
        return branch;
    }

    public void setBranch(String branch) {
        this.branch = branch;
    }

    public CreateBuildRequestDTO name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Name of the build
     *
     * @return name
     **/
    @Schema(required = true, description = "Name of the build")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateBuildRequestDTO createBuildRequestDTO = (CreateBuildRequestDTO) o;
        return Objects.equals(this.applicationCode, createBuildRequestDTO.applicationCode) && Objects.equals(this.branch, createBuildRequestDTO.branch) && Objects.equals(this.name, createBuildRequestDTO.name);
    }

    @Override
    public int hashCode() {
        return Objects.hash(applicationCode, branch, name);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreateBuildRequestDTO {\n");

        sb.append("    applicationCode: ").append(toIndentedString(applicationCode)).append("\n");
        sb.append("    branch: ").append(toIndentedString(branch)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
