/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

/**
 * Databackup
 */
@Schema(description = "Databackup")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T21:55:47.726988+02:00[Europe/Rome]")

public class DatabackupDetailDTO {
    @SerializedName("databackupCode")
    private String databackupCode = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("buildCode")
    private String buildCode = null;

    @SerializedName("status")
    private String status = null;

    @SerializedName("databackupType")
    private String databackupType = null;

    @SerializedName("description")
    private String description = null;

    @SerializedName("createdBy")
    private String createdBy = null;

    @SerializedName("createdTimestamp")
    private OffsetDateTime createdTimestamp = null;

    @SerializedName("canBeRestored")
    private Boolean canBeRestored = null;

    @SerializedName("canBeDeleted")
    private Boolean canBeDeleted = null;

    @SerializedName("canBeCanceled")
    private Boolean canBeCanceled = null;

    public DatabackupDetailDTO databackupCode(String databackupCode) {
        this.databackupCode = databackupCode;
        return this;
    }

    /**
     * Databackup Code
     *
     * @return databackupCode
     **/
    @Schema(description = "Databackup Code")
    public String getDatabackupCode() {
        return databackupCode;
    }

    public void setDatabackupCode(String databackupCode) {
        this.databackupCode = databackupCode;
    }

    public DatabackupDetailDTO name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Name
     *
     * @return name
     **/
    @Schema(description = "Name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public DatabackupDetailDTO buildCode(String buildCode) {
        this.buildCode = buildCode;
        return this;
    }

    /**
     * Build code
     *
     * @return buildCode
     **/
    @Schema(description = "Build code")
    public String getBuildCode() {
        return buildCode;
    }

    public void setBuildCode(String buildCode) {
        this.buildCode = buildCode;
    }

    public DatabackupDetailDTO status(String status) {
        this.status = status;
        return this;
    }

    /**
     * Status
     *
     * @return status
     **/
    @Schema(description = "Status")
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public DatabackupDetailDTO databackupType(String databackupType) {
        this.databackupType = databackupType;
        return this;
    }

    /**
     * Type
     *
     * @return databackupType
     **/
    @Schema(description = "Type")
    public String getDatabackupType() {
        return databackupType;
    }

    public void setDatabackupType(String databackupType) {
        this.databackupType = databackupType;
    }

    public DatabackupDetailDTO description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Description
     *
     * @return description
     **/
    @Schema(description = "Description")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public DatabackupDetailDTO createdBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * User that created the databackup
     *
     * @return createdBy
     **/
    @Schema(description = "User that created the databackup")
    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public DatabackupDetailDTO createdTimestamp(OffsetDateTime createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
        return this;
    }

    /**
     * Databackup creation timestamp
     *
     * @return createdTimestamp
     **/
    @Schema(description = "Databackup creation timestamp")
    public OffsetDateTime getCreatedTimestamp() {
        return createdTimestamp;
    }

    public void setCreatedTimestamp(OffsetDateTime createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }

    public DatabackupDetailDTO canBeRestored(Boolean canBeRestored) {
        this.canBeRestored = canBeRestored;
        return this;
    }

    /**
     * Can be restored
     *
     * @return canBeRestored
     **/
    @Schema(description = "Can be restored")
    public Boolean isCanBeRestored() {
        return canBeRestored;
    }

    public void setCanBeRestored(Boolean canBeRestored) {
        this.canBeRestored = canBeRestored;
    }

    public DatabackupDetailDTO canBeDeleted(Boolean canBeDeleted) {
        this.canBeDeleted = canBeDeleted;
        return this;
    }

    /**
     * Can be deleted
     *
     * @return canBeDeleted
     **/
    @Schema(description = "Can be deleted")
    public Boolean isCanBeDeleted() {
        return canBeDeleted;
    }

    public void setCanBeDeleted(Boolean canBeDeleted) {
        this.canBeDeleted = canBeDeleted;
    }

    public DatabackupDetailDTO canBeCanceled(Boolean canBeCanceled) {
        this.canBeCanceled = canBeCanceled;
        return this;
    }

    /**
     * Can be canceled
     *
     * @return canBeCanceled
     **/
    @Schema(description = "Can be canceled")
    public Boolean isCanBeCanceled() {
        return canBeCanceled;
    }

    public void setCanBeCanceled(Boolean canBeCanceled) {
        this.canBeCanceled = canBeCanceled;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DatabackupDetailDTO databackupDetailDTO = (DatabackupDetailDTO) o;
        return Objects.equals(this.databackupCode, databackupDetailDTO.databackupCode) && Objects.equals(this.name, databackupDetailDTO.name) && Objects.equals(this.buildCode, databackupDetailDTO.buildCode) && Objects.equals(this.status, databackupDetailDTO.status) && Objects.equals(this.databackupType, databackupDetailDTO.databackupType) && Objects.equals(this.description, databackupDetailDTO.description) && Objects.equals(this.createdBy, databackupDetailDTO.createdBy) && Objects.equals(this.createdTimestamp, databackupDetailDTO.createdTimestamp) && Objects.equals(this.canBeRestored, databackupDetailDTO.canBeRestored) && Objects.equals(this.canBeDeleted, databackupDetailDTO.canBeDeleted) && Objects.equals(this.canBeCanceled, databackupDetailDTO.canBeCanceled);
    }

    @Override
    public int hashCode() {
        return Objects.hash(databackupCode, name, buildCode, status, databackupType, description, createdBy, createdTimestamp, canBeRestored, canBeDeleted, canBeCanceled);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DatabackupDetailDTO {\n");

        sb.append("    databackupCode: ").append(toIndentedString(databackupCode)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    buildCode: ").append(toIndentedString(buildCode)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    databackupType: ").append(toIndentedString(databackupType)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
        sb.append("    createdTimestamp: ").append(toIndentedString(createdTimestamp)).append("\n");
        sb.append("    canBeRestored: ").append(toIndentedString(canBeRestored)).append("\n");
        sb.append("    canBeDeleted: ").append(toIndentedString(canBeDeleted)).append("\n");
        sb.append("    canBeCanceled: ").append(toIndentedString(canBeCanceled)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
