/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

/**
 * Datarestore
 */
@Schema(description = "Datarestore")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T21:55:47.726988+02:00[Europe/Rome]")

public class DatarestoreDetailDTO {
    @SerializedName("datarestoreCode")
    private String datarestoreCode = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("status")
    private String status = null;

    @SerializedName("databackupCode")
    private String databackupCode = null;

    @SerializedName("createdBy")
    private String createdBy = null;

    @SerializedName("createdTimestamp")
    private OffsetDateTime createdTimestamp = null;

    @SerializedName("canBeCanceled")
    private Boolean canBeCanceled = null;

    public DatarestoreDetailDTO datarestoreCode(String datarestoreCode) {
        this.datarestoreCode = datarestoreCode;
        return this;
    }

    /**
     * Datarestore Code
     *
     * @return datarestoreCode
     **/
    @Schema(description = "Datarestore Code")
    public String getDatarestoreCode() {
        return datarestoreCode;
    }

    public void setDatarestoreCode(String datarestoreCode) {
        this.datarestoreCode = datarestoreCode;
    }

    public DatarestoreDetailDTO name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Name
     *
     * @return name
     **/
    @Schema(description = "Name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public DatarestoreDetailDTO status(String status) {
        this.status = status;
        return this;
    }

    /**
     * Status
     *
     * @return status
     **/
    @Schema(description = "Status")
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public DatarestoreDetailDTO databackupCode(String databackupCode) {
        this.databackupCode = databackupCode;
        return this;
    }

    /**
     * Databackup that is the source of the datarestore
     *
     * @return databackupCode
     **/
    @Schema(description = "Databackup that is the source of the datarestore")
    public String getDatabackupCode() {
        return databackupCode;
    }

    public void setDatabackupCode(String databackupCode) {
        this.databackupCode = databackupCode;
    }

    public DatarestoreDetailDTO createdBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * User that started (created) the datarestore
     *
     * @return createdBy
     **/
    @Schema(description = "User that started (created) the datarestore")
    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public DatarestoreDetailDTO createdTimestamp(OffsetDateTime createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
        return this;
    }

    /**
     * Datarestore creation timestamp
     *
     * @return createdTimestamp
     **/
    @Schema(description = "Datarestore creation timestamp")
    public OffsetDateTime getCreatedTimestamp() {
        return createdTimestamp;
    }

    public void setCreatedTimestamp(OffsetDateTime createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }

    public DatarestoreDetailDTO canBeCanceled(Boolean canBeCanceled) {
        this.canBeCanceled = canBeCanceled;
        return this;
    }

    /**
     * Can be canceled
     *
     * @return canBeCanceled
     **/
    @Schema(description = "Can be canceled")
    public Boolean isCanBeCanceled() {
        return canBeCanceled;
    }

    public void setCanBeCanceled(Boolean canBeCanceled) {
        this.canBeCanceled = canBeCanceled;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DatarestoreDetailDTO datarestoreDetailDTO = (DatarestoreDetailDTO) o;
        return Objects.equals(this.datarestoreCode, datarestoreDetailDTO.datarestoreCode) && Objects.equals(this.name, datarestoreDetailDTO.name) && Objects.equals(this.status, datarestoreDetailDTO.status) && Objects.equals(this.databackupCode, datarestoreDetailDTO.databackupCode) && Objects.equals(this.createdBy, datarestoreDetailDTO.createdBy) && Objects.equals(this.createdTimestamp, datarestoreDetailDTO.createdTimestamp) && Objects.equals(this.canBeCanceled, datarestoreDetailDTO.canBeCanceled);
    }

    @Override
    public int hashCode() {
        return Objects.hash(datarestoreCode, name, status, databackupCode, createdBy, createdTimestamp, canBeCanceled);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DatarestoreDetailDTO {\n");

        sb.append("    datarestoreCode: ").append(toIndentedString(datarestoreCode)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    databackupCode: ").append(toIndentedString(databackupCode)).append("\n");
        sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
        sb.append("    createdTimestamp: ").append(toIndentedString(createdTimestamp)).append("\n");
        sb.append("    canBeCanceled: ").append(toIndentedString(canBeCanceled)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
