/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;

import java.io.IOException;
import java.util.Objects;

/**
 * Change datarestore
 */
@Schema(description = "Change datarestore")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T21:55:47.726988+02:00[Europe/Rome]")

public class DatarestoreStateChangeDTO {
    @SerializedName("action")
    private ActionEnum action = null;

    public DatarestoreStateChangeDTO action(ActionEnum action) {
        this.action = action;
        return this;
    }

    /**
     * Perform this action on the datarestore
     *
     * @return action
     **/
    @Schema(description = "Perform this action on the datarestore")
    public ActionEnum getAction() {
        return action;
    }

    public void setAction(ActionEnum action) {
        this.action = action;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DatarestoreStateChangeDTO datarestoreStateChangeDTO = (DatarestoreStateChangeDTO) o;
        return Objects.equals(this.action, datarestoreStateChangeDTO.action);
    }

    @Override
    public int hashCode() {
        return Objects.hash(action);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DatarestoreStateChangeDTO {\n");

        sb.append("    action: ").append(toIndentedString(action)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Perform this action on the datarestore
     */
    @JsonAdapter(ActionEnum.Adapter.class)
    public enum ActionEnum {
        @SerializedName("CANCEL") CANCEL("CANCEL");

        private String value;

        ActionEnum(String value) {
            this.value = value;
        }

        public static ActionEnum fromValue(String input) {
            for (ActionEnum b : ActionEnum.values()) {
                if (b.value.equals(input)) {
                    return b;
                }
            }
            return null;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static class Adapter extends TypeAdapter<ActionEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final ActionEnum enumeration) throws IOException {
                jsonWriter.value(String.valueOf(enumeration.getValue()));
            }

            @Override
            public ActionEnum read(final JsonReader jsonReader) throws IOException {
                Object value = jsonReader.nextString();
                return ActionEnum.fromValue((String) (value));
            }
        }
    }

}
