/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.cx.commercecloud.management.openapi.model.DatabasesBackup;
import com.sap.cx.commercecloud.management.openapi.model.StoragesBackup;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Content of a databackup
 */
@Schema(description = "Content of a databackup")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class DatabackupContent {
  @SerializedName("databasesBackup")
  private DatabasesBackup databasesBackup = null;

  @SerializedName("storagesBackup")
  private StoragesBackup storagesBackup = null;

  public DatabackupContent databasesBackup(DatabasesBackup databasesBackup) {
    this.databasesBackup = databasesBackup;
    return this;
  }

   /**
   * Get databasesBackup
   * @return databasesBackup
  **/
  @Schema(required = true, description = "")
  public DatabasesBackup getDatabasesBackup() {
    return databasesBackup;
  }

  public void setDatabasesBackup(DatabasesBackup databasesBackup) {
    this.databasesBackup = databasesBackup;
  }

  public DatabackupContent storagesBackup(StoragesBackup storagesBackup) {
    this.storagesBackup = storagesBackup;
    return this;
  }

   /**
   * Get storagesBackup
   * @return storagesBackup
  **/
  @Schema(required = true, description = "")
  public StoragesBackup getStoragesBackup() {
    return storagesBackup;
  }

  public void setStoragesBackup(StoragesBackup storagesBackup) {
    this.storagesBackup = storagesBackup;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatabackupContent databackupContent = (DatabackupContent) o;
    return Objects.equals(this.databasesBackup, databackupContent.databasesBackup) &&
        Objects.equals(this.storagesBackup, databackupContent.storagesBackup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(databasesBackup, storagesBackup);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatabackupContent {\n");
    
    sb.append("    databasesBackup: ").append(toIndentedString(databasesBackup)).append("\n");
    sb.append("    storagesBackup: ").append(toIndentedString(storagesBackup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
