/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * One deployment progress stage
 */
@Schema(description = "One deployment progress stage")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T21:55:47.726988+02:00[Europe/Rome]")

public class DeploymentProgressStageDTO {
    @SerializedName("name")
    private String name = null;

    @SerializedName("type")
    private String type = null;

    @SerializedName("startTimestamp")
    private OffsetDateTime startTimestamp = null;

    @SerializedName("endTimestamp")
    private OffsetDateTime endTimestamp = null;

    @SerializedName("status")
    private String status = null;

    @SerializedName("logLink")
    private String logLink = null;

    @SerializedName("steps")
    private List<DeploymentProgressStepDTO> steps = null;

    public DeploymentProgressStageDTO name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Name of the stage
     *
     * @return name
     **/
    @Schema(description = "Name of the stage")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public DeploymentProgressStageDTO type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Type of the stage
     *
     * @return type
     **/
    @Schema(description = "Type of the stage")
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public DeploymentProgressStageDTO startTimestamp(OffsetDateTime startTimestamp) {
        this.startTimestamp = startTimestamp;
        return this;
    }

    /**
     * Start timestamp of the stage
     *
     * @return startTimestamp
     **/
    @Schema(description = "Start timestamp of the stage")
    public OffsetDateTime getStartTimestamp() {
        return startTimestamp;
    }

    public void setStartTimestamp(OffsetDateTime startTimestamp) {
        this.startTimestamp = startTimestamp;
    }

    public DeploymentProgressStageDTO endTimestamp(OffsetDateTime endTimestamp) {
        this.endTimestamp = endTimestamp;
        return this;
    }

    /**
     * End timestamp of the stage
     *
     * @return endTimestamp
     **/
    @Schema(description = "End timestamp of the stage")
    public OffsetDateTime getEndTimestamp() {
        return endTimestamp;
    }

    public void setEndTimestamp(OffsetDateTime endTimestamp) {
        this.endTimestamp = endTimestamp;
    }

    public DeploymentProgressStageDTO status(String status) {
        this.status = status;
        return this;
    }

    /**
     * Current status of the stage, possible values are \&quot;PENDING\&quot;,\&quot;RUNNING\&quot;,\&quot;DONE\&quot; or \&quot;FAIL\&quot;
     *
     * @return status
     **/
    @Schema(description = "Current status of the stage, possible values are \"PENDING\",\"RUNNING\",\"DONE\" or \"FAIL\"")
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public DeploymentProgressStageDTO logLink(String logLink) {
        this.logLink = logLink;
        return this;
    }

    /**
     * Link to logs of the stage
     *
     * @return logLink
     **/
    @Schema(description = "Link to logs of the stage")
    public String getLogLink() {
        return logLink;
    }

    public void setLogLink(String logLink) {
        this.logLink = logLink;
    }

    public DeploymentProgressStageDTO steps(List<DeploymentProgressStepDTO> steps) {
        this.steps = steps;
        return this;
    }

    public DeploymentProgressStageDTO addStepsItem(DeploymentProgressStepDTO stepsItem) {
        if (this.steps == null) {
            this.steps = new ArrayList<DeploymentProgressStepDTO>();
        }
        this.steps.add(stepsItem);
        return this;
    }

    /**
     * One or multiple deployment progress steps
     *
     * @return steps
     **/
    @Schema(description = "One or multiple deployment progress steps")
    public List<DeploymentProgressStepDTO> getSteps() {
        return steps;
    }

    public void setSteps(List<DeploymentProgressStepDTO> steps) {
        this.steps = steps;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeploymentProgressStageDTO deploymentProgressStageDTO = (DeploymentProgressStageDTO) o;
        return Objects.equals(this.name, deploymentProgressStageDTO.name) && Objects.equals(this.type, deploymentProgressStageDTO.type) && Objects.equals(this.startTimestamp, deploymentProgressStageDTO.startTimestamp) && Objects.equals(this.endTimestamp, deploymentProgressStageDTO.endTimestamp) && Objects.equals(this.status, deploymentProgressStageDTO.status) && Objects.equals(this.logLink, deploymentProgressStageDTO.logLink) && Objects.equals(this.steps, deploymentProgressStageDTO.steps);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, type, startTimestamp, endTimestamp, status, logLink, steps);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DeploymentProgressStageDTO {\n");

        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    startTimestamp: ").append(toIndentedString(startTimestamp)).append("\n");
        sb.append("    endTimestamp: ").append(toIndentedString(endTimestamp)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    logLink: ").append(toIndentedString(logLink)).append("\n");
        sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
