/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Deployment progress insight with several stages
 */
@Schema(description = "Deployment progress insight with several stages")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T21:55:47.726988+02:00[Europe/Rome]")

public class DeploymentProgressDTO {
    public DeploymentProgressDTO() {
    }

    @SerializedName("subscriptionCode")
    private String subscriptionCode = null;

    @SerializedName("deploymentCode")
    private String deploymentCode = null;

    @SerializedName("deploymentStatus")
    private String deploymentStatus = null;

    @SerializedName("percentage")
    private Integer percentage = null;

    @SerializedName("stages")
    private List<DeploymentProgressStageDTO> stages = null;

    public DeploymentProgressDTO subscriptionCode(String subscriptionCode) {
        this.subscriptionCode = subscriptionCode;
        return this;
    }

    /**
     * Code of the subscription
     *
     * @return subscriptionCode
     **/
    @Schema(description = "Code of the subscription")
    public String getSubscriptionCode() {
        return subscriptionCode;
    }

    public void setSubscriptionCode(String subscriptionCode) {
        this.subscriptionCode = subscriptionCode;
    }

    public DeploymentProgressDTO deploymentCode(String deploymentCode) {
        this.deploymentCode = deploymentCode;
        return this;
    }

    /**
     * Code of the deployment
     *
     * @return deploymentCode
     **/
    @Schema(description = "Code of the deployment")
    public String getDeploymentCode() {
        return deploymentCode;
    }

    public void setDeploymentCode(String deploymentCode) {
        this.deploymentCode = deploymentCode;
    }

    public DeploymentProgressDTO deploymentStatus(String deploymentStatus) {
        this.deploymentStatus = deploymentStatus;
        return this;
    }

    /**
     * Status of the current deployment, possible values are \&quot;SCHEDULED\&quot;,\&quot;DEPLOYING\&quot;,\&quot;DEPLOYED\&quot;,\&quot;UNDEPLOYED\&quot; or \&quot;FAIL\&quot;
     *
     * @return deploymentStatus
     **/
    @Schema(description = "Status of the current deployment, possible values are \"SCHEDULED\",\"DEPLOYING\",\"DEPLOYED\",\"UNDEPLOYED\" or \"FAIL\"")
    public String getDeploymentStatus() {
        return deploymentStatus;
    }

    public void setDeploymentStatus(String deploymentStatus) {
        this.deploymentStatus = deploymentStatus;
    }

    public DeploymentProgressDTO percentage(Integer percentage) {
        this.percentage = percentage;
        return this;
    }

    /**
     * Completion percentage calculated by checking how many items are now running/finished/failed
     *
     * @return percentage
     **/
    @Schema(description = "Completion percentage calculated by checking how many items are now running/finished/failed")
    public Integer getPercentage() {
        return percentage;
    }

    public void setPercentage(Integer percentage) {
        this.percentage = percentage;
    }

    public DeploymentProgressDTO stages(List<DeploymentProgressStageDTO> stages) {
        this.stages = stages;
        return this;
    }

    public DeploymentProgressDTO addStagesItem(DeploymentProgressStageDTO stagesItem) {
        if (this.stages == null) {
            this.stages = new ArrayList<DeploymentProgressStageDTO>();
        }
        this.stages.add(stagesItem);
        return this;
    }

    /**
     * One or multiple deployment progress stages with individual steps
     *
     * @return stages
     **/
    @Schema(description = "One or multiple deployment progress stages with individual steps")
    public List<DeploymentProgressStageDTO> getStages() {
        return stages;
    }

    public void setStages(List<DeploymentProgressStageDTO> stages) {
        this.stages = stages;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeploymentProgressDTO deploymentProgressDTO = (DeploymentProgressDTO) o;
        return Objects.equals(this.subscriptionCode, deploymentProgressDTO.subscriptionCode) && Objects.equals(this.deploymentCode, deploymentProgressDTO.deploymentCode) && Objects.equals(this.deploymentStatus, deploymentProgressDTO.deploymentStatus) && Objects.equals(this.percentage, deploymentProgressDTO.percentage) && Objects.equals(this.stages, deploymentProgressDTO.stages);
    }

    @Override
    public int hashCode() {
        return Objects.hash(subscriptionCode, deploymentCode, deploymentStatus, percentage, stages);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DeploymentProgressDTO {\n");

        sb.append("    subscriptionCode: ").append(toIndentedString(subscriptionCode)).append("\n");
        sb.append("    deploymentCode: ").append(toIndentedString(deploymentCode)).append("\n");
        sb.append("    deploymentStatus: ").append(toIndentedString(deploymentStatus)).append("\n");
        sb.append("    percentage: ").append(toIndentedString(percentage)).append("\n");
        sb.append("    stages: ").append(toIndentedString(stages)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
