/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

/**
 * Deployment cancelation options detail
 */
@Schema(description = "Deployment cancelation options detail")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T21:55:47.726988+02:00[Europe/Rome]")

public class DeploymentCancellationOptionsDetailDTO {
    public DeploymentCancellationOptionsDetailDTO() {
    }

    @SerializedName("databaseRollbackRestoreTimestamp")
    private OffsetDateTime databaseRollbackRestoreTimestamp = null;

    public DeploymentCancellationOptionsDetailDTO databaseRollbackRestoreTimestamp(OffsetDateTime databaseRollbackRestoreTimestamp) {
        this.databaseRollbackRestoreTimestamp = databaseRollbackRestoreTimestamp;
        return this;
    }

    /**
     * Time the database can be rolled back to
     *
     * @return databaseRollbackRestoreTimestamp
     **/
    @Schema(description = "Time the database can be rolled back to")
    public OffsetDateTime getDatabaseRollbackRestoreTimestamp() {
        return databaseRollbackRestoreTimestamp;
    }

    public void setDatabaseRollbackRestoreTimestamp(OffsetDateTime databaseRollbackRestoreTimestamp) {
        this.databaseRollbackRestoreTimestamp = databaseRollbackRestoreTimestamp;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeploymentCancellationOptionsDetailDTO deploymentCancellationOptionsDetailDTO = (DeploymentCancellationOptionsDetailDTO) o;
        return Objects.equals(this.databaseRollbackRestoreTimestamp, deploymentCancellationOptionsDetailDTO.databaseRollbackRestoreTimestamp);
    }

    @Override
    public int hashCode() {
        return Objects.hash(databaseRollbackRestoreTimestamp);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DeploymentCancellationOptionsDetailDTO {\n");

        sb.append("    databaseRollbackRestoreTimestamp: ").append(toIndentedString(databaseRollbackRestoreTimestamp)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
