/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Deployment decisions
 */
@Schema(description = "Deployment decisions")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T21:55:47.726988+02:00[Europe/Rome]")

public class DeploymentDecisionsDTO {

    public DeploymentDecisionsDTO() {
    }

    @SerializedName("deploymentDecisions")
    private List<DeploymentDecisionDTO> deploymentDecisions = null;

    public DeploymentDecisionsDTO deploymentDecisions(List<DeploymentDecisionDTO> deploymentDecisions) {
        this.deploymentDecisions = deploymentDecisions;
        return this;
    }

    public DeploymentDecisionsDTO addDeploymentDecisionsItem(DeploymentDecisionDTO deploymentDecisionsItem) {
        if (this.deploymentDecisions == null) {
            this.deploymentDecisions = new ArrayList<DeploymentDecisionDTO>();
        }
        this.deploymentDecisions.add(deploymentDecisionsItem);
        return this;
    }

    /**
     * Get deploymentDecisions
     *
     * @return deploymentDecisions
     **/
    @Schema(description = "")
    public List<DeploymentDecisionDTO> getDeploymentDecisions() {
        return deploymentDecisions;
    }

    public void setDeploymentDecisions(List<DeploymentDecisionDTO> deploymentDecisions) {
        this.deploymentDecisions = deploymentDecisions;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeploymentDecisionsDTO deploymentDecisionsDTO = (DeploymentDecisionsDTO) o;
        return Objects.equals(this.deploymentDecisions, deploymentDecisionsDTO.deploymentDecisions);
    }

    @Override
    public int hashCode() {
        return Objects.hash(deploymentDecisions);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DeploymentDecisionsDTO {\n");

        sb.append("    deploymentDecisions: ").append(toIndentedString(deploymentDecisions)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
