/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Details of a deploymentmodes per environment
 */
@Schema(description = "Details of a deploymentmodes per environment")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T21:55:47.726988+02:00[Europe/Rome]")

public class DeploymentModesPerEnvironmentDTO {
    public DeploymentModesPerEnvironmentDTO() {
    }

    @SerializedName("environmentCode")
    private String environmentCode = null;

    @SerializedName("deploymentModes")
    private DeploymentModeDTO deploymentModes = null;

    public DeploymentModesPerEnvironmentDTO environmentCode(String environmentCode) {
        this.environmentCode = environmentCode;
        return this;
    }

    /**
     * Environment code
     *
     * @return environmentCode
     **/
    @Schema(description = "Environment code")
    public String getEnvironmentCode() {
        return environmentCode;
    }

    public void setEnvironmentCode(String environmentCode) {
        this.environmentCode = environmentCode;
    }

    public DeploymentModesPerEnvironmentDTO deploymentModes(DeploymentModeDTO deploymentModes) {
        this.deploymentModes = deploymentModes;
        return this;
    }

    /**
     * Get deploymentModes
     *
     * @return deploymentModes
     **/
    @Schema(description = "")
    public DeploymentModeDTO getDeploymentModes() {
        return deploymentModes;
    }

    public void setDeploymentModes(DeploymentModeDTO deploymentModes) {
        this.deploymentModes = deploymentModes;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeploymentModesPerEnvironmentDTO deploymentModesPerEnvironmentDTO = (DeploymentModesPerEnvironmentDTO) o;
        return Objects.equals(this.environmentCode, deploymentModesPerEnvironmentDTO.environmentCode) && Objects.equals(this.deploymentModes, deploymentModesPerEnvironmentDTO.deploymentModes);
    }

    @Override
    public int hashCode() {
        return Objects.hash(environmentCode, deploymentModes);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DeploymentModesPerEnvironmentDTO {\n");

        sb.append("    environmentCode: ").append(toIndentedString(environmentCode)).append("\n");
        sb.append("    deploymentModes: ").append(toIndentedString(deploymentModes)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
