/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.cx.commercecloud.management.openapi.model.CachingDTO;
import com.sap.cx.commercecloud.management.openapi.model.EndpointWafConfigurationDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * EndpointDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class EndpointDTO {
  @SerializedName("code")
  private String code = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("priority")
  private Integer priority = null;

  @SerializedName("domainName")
  private String domainName = null;

  /**
   * Transfer protocol. HTTP or HTTPS
   */
  @JsonAdapter(ProtocolEnum.Adapter.class)
  public enum ProtocolEnum {
    @SerializedName("HTTP")
    HTTP("HTTP"),
    @SerializedName("HTTPS")
    HTTPS("HTTPS");

    private String value;

    ProtocolEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static ProtocolEnum fromValue(String input) {
      for (ProtocolEnum b : ProtocolEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<ProtocolEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ProtocolEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public ProtocolEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return ProtocolEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("protocol")
  private ProtocolEnum protocol = null;

  @SerializedName("k8sService")
  private String k8sService = null;

  /**
   * K8s service version
   */
  @JsonAdapter(K8sServiceVersionEnum.Adapter.class)
  public enum K8sServiceVersionEnum {
    @SerializedName("GREEN")
    GREEN("GREEN"),
    @SerializedName("BLUE")
    BLUE("BLUE"),
    @SerializedName("UNSPECIFIED")
    UNSPECIFIED("UNSPECIFIED");

    private String value;

    K8sServiceVersionEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static K8sServiceVersionEnum fromValue(String input) {
      for (K8sServiceVersionEnum b : K8sServiceVersionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<K8sServiceVersionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final K8sServiceVersionEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public K8sServiceVersionEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return K8sServiceVersionEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("k8sServiceVersion")
  private K8sServiceVersionEnum k8sServiceVersion = null;

  @SerializedName("proxyTimeOut")
  private Integer proxyTimeOut = null;

  /**
   * Access type for this endpoint. Choices are ALLOW_ALL or DENY_ALL
   */
  @JsonAdapter(AccessEnum.Adapter.class)
  public enum AccessEnum {
    @SerializedName("ALLOW_ALL")
    ALLOW_ALL("ALLOW_ALL"),
    @SerializedName("DENY_ALL")
    DENY_ALL("DENY_ALL");

    private String value;

    AccessEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static AccessEnum fromValue(String input) {
      for (AccessEnum b : AccessEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<AccessEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AccessEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public AccessEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return AccessEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("access")
  private AccessEnum access = null;

  @SerializedName("sslCertificate")
  private String sslCertificate = null;

  @SerializedName("mtlsCertificateCode")
  private String mtlsCertificateCode = null;

  @SerializedName("mtlsAllowedDomains")
  private List<String> mtlsAllowedDomains = null;

  @SerializedName("ipFilteringSets")
  private List<String> ipFilteringSets = null;

  @SerializedName("redirectSets")
  private List<String> redirectSets = null;

  @SerializedName("staticFileSet")
  private String staticFileSet = null;

  @SerializedName("denyPathsSet")
  private String denyPathsSet = null;

  @SerializedName("webProxy")
  private String webProxy = null;

  @SerializedName("responseHeaderSet")
  private String responseHeaderSet = null;

  @SerializedName("maintenanceMode")
  private Boolean maintenanceMode = null;

  @SerializedName("caching")
  private CachingDTO caching = null;

  @SerializedName("wafConfig")
  private EndpointWafConfigurationDTO wafConfig = null;

  public EndpointDTO code(String code) {
    this.code = code;
    return this;
  }

   /**
   * The code of an endpoint
   * @return code
  **/
  @Schema(description = "The code of an endpoint")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public EndpointDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of an endpoint
   * @return name
  **/
  @Schema(required = true, description = "The name of an endpoint")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public EndpointDTO description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The description of an endpoint
   * @return description
  **/
  @Schema(description = "The description of an endpoint")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public EndpointDTO priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * The priority of an endpoint
   * @return priority
  **/
  @Schema(description = "The priority of an endpoint")
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public EndpointDTO domainName(String domainName) {
    this.domainName = domainName;
    return this;
  }

   /**
   * Domain URL of this endpoint, without a path or protocol
   * @return domainName
  **/
  @Schema(required = true, description = "Domain URL of this endpoint, without a path or protocol")
  public String getDomainName() {
    return domainName;
  }

  public void setDomainName(String domainName) {
    this.domainName = domainName;
  }

  public EndpointDTO protocol(ProtocolEnum protocol) {
    this.protocol = protocol;
    return this;
  }

   /**
   * Transfer protocol. HTTP or HTTPS
   * @return protocol
  **/
  @Schema(required = true, description = "Transfer protocol. HTTP or HTTPS")
  public ProtocolEnum getProtocol() {
    return protocol;
  }

  public void setProtocol(ProtocolEnum protocol) {
    this.protocol = protocol;
  }

  public EndpointDTO k8sService(String k8sService) {
    this.k8sService = k8sService;
    return this;
  }

   /**
   * A K8s service behind this endpoint
   * @return k8sService
  **/
  @Schema(required = true, description = "A K8s service behind this endpoint")
  public String getK8sService() {
    return k8sService;
  }

  public void setK8sService(String k8sService) {
    this.k8sService = k8sService;
  }

  public EndpointDTO k8sServiceVersion(K8sServiceVersionEnum k8sServiceVersion) {
    this.k8sServiceVersion = k8sServiceVersion;
    return this;
  }

   /**
   * K8s service version
   * @return k8sServiceVersion
  **/
  @Schema(required = true, description = "K8s service version")
  public K8sServiceVersionEnum getK8sServiceVersion() {
    return k8sServiceVersion;
  }

  public void setK8sServiceVersion(K8sServiceVersionEnum k8sServiceVersion) {
    this.k8sServiceVersion = k8sServiceVersion;
  }

  public EndpointDTO proxyTimeOut(Integer proxyTimeOut) {
    this.proxyTimeOut = proxyTimeOut;
    return this;
  }

   /**
   * The time out in seconds for the endpoint on the Ingress
   * minimum: 0
   * @return proxyTimeOut
  **/
  @Schema(description = "The time out in seconds for the endpoint on the Ingress")
  public Integer getProxyTimeOut() {
    return proxyTimeOut;
  }

  public void setProxyTimeOut(Integer proxyTimeOut) {
    this.proxyTimeOut = proxyTimeOut;
  }

  public EndpointDTO access(AccessEnum access) {
    this.access = access;
    return this;
  }

   /**
   * Access type for this endpoint. Choices are ALLOW_ALL or DENY_ALL
   * @return access
  **/
  @Schema(required = true, description = "Access type for this endpoint. Choices are ALLOW_ALL or DENY_ALL")
  public AccessEnum getAccess() {
    return access;
  }

  public void setAccess(AccessEnum access) {
    this.access = access;
  }

  public EndpointDTO sslCertificate(String sslCertificate) {
    this.sslCertificate = sslCertificate;
    return this;
  }

   /**
   * The code of the SSL Certificate
   * @return sslCertificate
  **/
  @Schema(description = "The code of the SSL Certificate")
  public String getSslCertificate() {
    return sslCertificate;
  }

  public void setSslCertificate(String sslCertificate) {
    this.sslCertificate = sslCertificate;
  }

  public EndpointDTO mtlsCertificateCode(String mtlsCertificateCode) {
    this.mtlsCertificateCode = mtlsCertificateCode;
    return this;
  }

   /**
   * The code of mTLS Certificate
   * @return mtlsCertificateCode
  **/
  @Schema(description = "The code of mTLS Certificate")
  public String getMtlsCertificateCode() {
    return mtlsCertificateCode;
  }

  public void setMtlsCertificateCode(String mtlsCertificateCode) {
    this.mtlsCertificateCode = mtlsCertificateCode;
  }

  public EndpointDTO mtlsAllowedDomains(List<String> mtlsAllowedDomains) {
    this.mtlsAllowedDomains = mtlsAllowedDomains;
    return this;
  }

  public EndpointDTO addMtlsAllowedDomainsItem(String mtlsAllowedDomainsItem) {
    if (this.mtlsAllowedDomains == null) {
      this.mtlsAllowedDomains = new ArrayList<String>();
    }
    this.mtlsAllowedDomains.add(mtlsAllowedDomainsItem);
    return this;
  }

   /**
   * The list of allowed domains for mTLS
   * @return mtlsAllowedDomains
  **/
  @Schema(description = "The list of allowed domains for mTLS")
  public List<String> getMtlsAllowedDomains() {
    return mtlsAllowedDomains;
  }

  public void setMtlsAllowedDomains(List<String> mtlsAllowedDomains) {
    this.mtlsAllowedDomains = mtlsAllowedDomains;
  }

  public EndpointDTO ipFilteringSets(List<String> ipFilteringSets) {
    this.ipFilteringSets = ipFilteringSets;
    return this;
  }

  public EndpointDTO addIpFilteringSetsItem(String ipFilteringSetsItem) {
    if (this.ipFilteringSets == null) {
      this.ipFilteringSets = new ArrayList<String>();
    }
    this.ipFilteringSets.add(ipFilteringSetsItem);
    return this;
  }

   /**
   * The list of IP filtering set codes
   * @return ipFilteringSets
  **/
  @Schema(description = "The list of IP filtering set codes")
  public List<String> getIpFilteringSets() {
    return ipFilteringSets;
  }

  public void setIpFilteringSets(List<String> ipFilteringSets) {
    this.ipFilteringSets = ipFilteringSets;
  }

  public EndpointDTO redirectSets(List<String> redirectSets) {
    this.redirectSets = redirectSets;
    return this;
  }

  public EndpointDTO addRedirectSetsItem(String redirectSetsItem) {
    if (this.redirectSets == null) {
      this.redirectSets = new ArrayList<String>();
    }
    this.redirectSets.add(redirectSetsItem);
    return this;
  }

   /**
   * The list of redirect set codes
   * @return redirectSets
  **/
  @Schema(description = "The list of redirect set codes")
  public List<String> getRedirectSets() {
    return redirectSets;
  }

  public void setRedirectSets(List<String> redirectSets) {
    this.redirectSets = redirectSets;
  }

  public EndpointDTO staticFileSet(String staticFileSet) {
    this.staticFileSet = staticFileSet;
    return this;
  }

   /**
   * The static file set code
   * @return staticFileSet
  **/
  @Schema(description = "The static file set code")
  public String getStaticFileSet() {
    return staticFileSet;
  }

  public void setStaticFileSet(String staticFileSet) {
    this.staticFileSet = staticFileSet;
  }

  public EndpointDTO denyPathsSet(String denyPathsSet) {
    this.denyPathsSet = denyPathsSet;
    return this;
  }

   /**
   * The deny paths set code
   * @return denyPathsSet
  **/
  @Schema(description = "The deny paths set code")
  public String getDenyPathsSet() {
    return denyPathsSet;
  }

  public void setDenyPathsSet(String denyPathsSet) {
    this.denyPathsSet = denyPathsSet;
  }

  public EndpointDTO webProxy(String webProxy) {
    this.webProxy = webProxy;
    return this;
  }

   /**
   * The web proxy code
   * @return webProxy
  **/
  @Schema(description = "The web proxy code")
  public String getWebProxy() {
    return webProxy;
  }

  public void setWebProxy(String webProxy) {
    this.webProxy = webProxy;
  }

  public EndpointDTO responseHeaderSet(String responseHeaderSet) {
    this.responseHeaderSet = responseHeaderSet;
    return this;
  }

   /**
   * The response header set code
   * @return responseHeaderSet
  **/
  @Schema(description = "The response header set code")
  public String getResponseHeaderSet() {
    return responseHeaderSet;
  }

  public void setResponseHeaderSet(String responseHeaderSet) {
    this.responseHeaderSet = responseHeaderSet;
  }

  public EndpointDTO maintenanceMode(Boolean maintenanceMode) {
    this.maintenanceMode = maintenanceMode;
    return this;
  }

   /**
   * Maintenance mode for this endpoint
   * @return maintenanceMode
  **/
  @Schema(description = "Maintenance mode for this endpoint")
  public Boolean isMaintenanceMode() {
    return maintenanceMode;
  }

  public void setMaintenanceMode(Boolean maintenanceMode) {
    this.maintenanceMode = maintenanceMode;
  }

  public EndpointDTO caching(CachingDTO caching) {
    this.caching = caching;
    return this;
  }

   /**
   * Get caching
   * @return caching
  **/
  @Schema(description = "")
  public CachingDTO getCaching() {
    return caching;
  }

  public void setCaching(CachingDTO caching) {
    this.caching = caching;
  }

  public EndpointDTO wafConfig(EndpointWafConfigurationDTO wafConfig) {
    this.wafConfig = wafConfig;
    return this;
  }

   /**
   * Get wafConfig
   * @return wafConfig
  **/
  @Schema(description = "")
  public EndpointWafConfigurationDTO getWafConfig() {
    return wafConfig;
  }

  public void setWafConfig(EndpointWafConfigurationDTO wafConfig) {
    this.wafConfig = wafConfig;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EndpointDTO endpointDTO = (EndpointDTO) o;
    return Objects.equals(this.code, endpointDTO.code) &&
        Objects.equals(this.name, endpointDTO.name) &&
        Objects.equals(this.description, endpointDTO.description) &&
        Objects.equals(this.priority, endpointDTO.priority) &&
        Objects.equals(this.domainName, endpointDTO.domainName) &&
        Objects.equals(this.protocol, endpointDTO.protocol) &&
        Objects.equals(this.k8sService, endpointDTO.k8sService) &&
        Objects.equals(this.k8sServiceVersion, endpointDTO.k8sServiceVersion) &&
        Objects.equals(this.proxyTimeOut, endpointDTO.proxyTimeOut) &&
        Objects.equals(this.access, endpointDTO.access) &&
        Objects.equals(this.sslCertificate, endpointDTO.sslCertificate) &&
        Objects.equals(this.mtlsCertificateCode, endpointDTO.mtlsCertificateCode) &&
        Objects.equals(this.mtlsAllowedDomains, endpointDTO.mtlsAllowedDomains) &&
        Objects.equals(this.ipFilteringSets, endpointDTO.ipFilteringSets) &&
        Objects.equals(this.redirectSets, endpointDTO.redirectSets) &&
        Objects.equals(this.staticFileSet, endpointDTO.staticFileSet) &&
        Objects.equals(this.denyPathsSet, endpointDTO.denyPathsSet) &&
        Objects.equals(this.webProxy, endpointDTO.webProxy) &&
        Objects.equals(this.responseHeaderSet, endpointDTO.responseHeaderSet) &&
        Objects.equals(this.maintenanceMode, endpointDTO.maintenanceMode) &&
        Objects.equals(this.caching, endpointDTO.caching) &&
        Objects.equals(this.wafConfig, endpointDTO.wafConfig);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, name, description, priority, domainName, protocol, k8sService, k8sServiceVersion, proxyTimeOut, access, sslCertificate, mtlsCertificateCode, mtlsAllowedDomains, ipFilteringSets, redirectSets, staticFileSet, denyPathsSet, webProxy, responseHeaderSet, maintenanceMode, caching, wafConfig);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EndpointDTO {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    domainName: ").append(toIndentedString(domainName)).append("\n");
    sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
    sb.append("    k8sService: ").append(toIndentedString(k8sService)).append("\n");
    sb.append("    k8sServiceVersion: ").append(toIndentedString(k8sServiceVersion)).append("\n");
    sb.append("    proxyTimeOut: ").append(toIndentedString(proxyTimeOut)).append("\n");
    sb.append("    access: ").append(toIndentedString(access)).append("\n");
    sb.append("    sslCertificate: ").append(toIndentedString(sslCertificate)).append("\n");
    sb.append("    mtlsCertificateCode: ").append(toIndentedString(mtlsCertificateCode)).append("\n");
    sb.append("    mtlsAllowedDomains: ").append(toIndentedString(mtlsAllowedDomains)).append("\n");
    sb.append("    ipFilteringSets: ").append(toIndentedString(ipFilteringSets)).append("\n");
    sb.append("    redirectSets: ").append(toIndentedString(redirectSets)).append("\n");
    sb.append("    staticFileSet: ").append(toIndentedString(staticFileSet)).append("\n");
    sb.append("    denyPathsSet: ").append(toIndentedString(denyPathsSet)).append("\n");
    sb.append("    webProxy: ").append(toIndentedString(webProxy)).append("\n");
    sb.append("    responseHeaderSet: ").append(toIndentedString(responseHeaderSet)).append("\n");
    sb.append("    maintenanceMode: ").append(toIndentedString(maintenanceMode)).append("\n");
    sb.append("    caching: ").append(toIndentedString(caching)).append("\n");
    sb.append("    wafConfig: ").append(toIndentedString(wafConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
