/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.cx.commercecloud.management.openapi.model.RateLimitingDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * EndpointWafConfigurationDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class EndpointWafConfigurationDTO {
  @SerializedName("rateLimiting")
  private RateLimitingDTO rateLimiting = null;

  public EndpointWafConfigurationDTO rateLimiting(RateLimitingDTO rateLimiting) {
    this.rateLimiting = rateLimiting;
    return this;
  }

   /**
   * Get rateLimiting
   * @return rateLimiting
  **/
  @Schema(description = "")
  public RateLimitingDTO getRateLimiting() {
    return rateLimiting;
  }

  public void setRateLimiting(RateLimitingDTO rateLimiting) {
    this.rateLimiting = rateLimiting;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EndpointWafConfigurationDTO endpointWafConfigurationDTO = (EndpointWafConfigurationDTO) o;
    return Objects.equals(this.rateLimiting, endpointWafConfigurationDTO.rateLimiting);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rateLimiting);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EndpointWafConfigurationDTO {\n");
    
    sb.append("    rateLimiting: ").append(toIndentedString(rateLimiting)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
