/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.cx.commercecloud.management.openapi.model.EnvironmentKubernetesClusterWorkerVmTypeDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Cluster details
 */
@Schema(description = "Cluster details")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class EnvironmentKubernetesClusterScalingDetailDTO {
  @SerializedName("code")
  private String code = null;

  @SerializedName("maxWorkerCount")
  private Integer maxWorkerCount = null;

  @SerializedName("workerVmType")
  private EnvironmentKubernetesClusterWorkerVmTypeDTO workerVmType = null;

  public EnvironmentKubernetesClusterScalingDetailDTO code(String code) {
    this.code = code;
    return this;
  }

   /**
   * code
   * @return code
  **/
  @Schema(required = true, description = "code")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public EnvironmentKubernetesClusterScalingDetailDTO maxWorkerCount(Integer maxWorkerCount) {
    this.maxWorkerCount = maxWorkerCount;
    return this;
  }

   /**
   * maxWorkerCount
   * @return maxWorkerCount
  **/
  @Schema(description = "maxWorkerCount")
  public Integer getMaxWorkerCount() {
    return maxWorkerCount;
  }

  public void setMaxWorkerCount(Integer maxWorkerCount) {
    this.maxWorkerCount = maxWorkerCount;
  }

  public EnvironmentKubernetesClusterScalingDetailDTO workerVmType(EnvironmentKubernetesClusterWorkerVmTypeDTO workerVmType) {
    this.workerVmType = workerVmType;
    return this;
  }

   /**
   * Get workerVmType
   * @return workerVmType
  **/
  @Schema(description = "")
  public EnvironmentKubernetesClusterWorkerVmTypeDTO getWorkerVmType() {
    return workerVmType;
  }

  public void setWorkerVmType(EnvironmentKubernetesClusterWorkerVmTypeDTO workerVmType) {
    this.workerVmType = workerVmType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnvironmentKubernetesClusterScalingDetailDTO environmentKubernetesClusterScalingDetailDTO = (EnvironmentKubernetesClusterScalingDetailDTO) o;
    return Objects.equals(this.code, environmentKubernetesClusterScalingDetailDTO.code) &&
        Objects.equals(this.maxWorkerCount, environmentKubernetesClusterScalingDetailDTO.maxWorkerCount) &&
        Objects.equals(this.workerVmType, environmentKubernetesClusterScalingDetailDTO.workerVmType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, maxWorkerCount, workerVmType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnvironmentKubernetesClusterScalingDetailDTO {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    maxWorkerCount: ").append(toIndentedString(maxWorkerCount)).append("\n");
    sb.append("    workerVmType: ").append(toIndentedString(workerVmType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
