/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
/**
 * Service scaling option
 */
@Schema(description = "Service scaling option")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class EnvironmentServiceScalingOptionDTO {
  @SerializedName("memoryScaleFactor")
  private List<BigDecimal> memoryScaleFactor = null;

  public EnvironmentServiceScalingOptionDTO memoryScaleFactor(List<BigDecimal> memoryScaleFactor) {
    this.memoryScaleFactor = memoryScaleFactor;
    return this;
  }

  public EnvironmentServiceScalingOptionDTO addMemoryScaleFactorItem(BigDecimal memoryScaleFactorItem) {
    if (this.memoryScaleFactor == null) {
      this.memoryScaleFactor = new ArrayList<BigDecimal>();
    }
    this.memoryScaleFactor.add(memoryScaleFactorItem);
    return this;
  }

   /**
   * memoryScaleFactor
   * @return memoryScaleFactor
  **/
  @Schema(description = "memoryScaleFactor")
  public List<BigDecimal> getMemoryScaleFactor() {
    return memoryScaleFactor;
  }

  public void setMemoryScaleFactor(List<BigDecimal> memoryScaleFactor) {
    this.memoryScaleFactor = memoryScaleFactor;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnvironmentServiceScalingOptionDTO environmentServiceScalingOptionDTO = (EnvironmentServiceScalingOptionDTO) o;
    return Objects.equals(this.memoryScaleFactor, environmentServiceScalingOptionDTO.memoryScaleFactor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(memoryScaleFactor);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnvironmentServiceScalingOptionDTO {\n");
    
    sb.append("    memoryScaleFactor: ").append(toIndentedString(memoryScaleFactor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
