/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.cx.commercecloud.management.openapi.model.EnvironmentDatabaseSchemaPerformanceDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Database scaling option
 */
@Schema(description = "Database scaling option")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class EnvironmentDatabaseSchemaScalingOptionDTO {
  @SerializedName("maxSizesInMb")
  private List<Long> maxSizesInMb = null;

  @SerializedName("performance")
  private EnvironmentDatabaseSchemaPerformanceDTO performance = null;

  public EnvironmentDatabaseSchemaScalingOptionDTO maxSizesInMb(List<Long> maxSizesInMb) {
    this.maxSizesInMb = maxSizesInMb;
    return this;
  }

  public EnvironmentDatabaseSchemaScalingOptionDTO addMaxSizesInMbItem(Long maxSizesInMbItem) {
    if (this.maxSizesInMb == null) {
      this.maxSizesInMb = new ArrayList<Long>();
    }
    this.maxSizesInMb.add(maxSizesInMbItem);
    return this;
  }

   /**
   * maxSizesInMb
   * @return maxSizesInMb
  **/
  @Schema(description = "maxSizesInMb")
  public List<Long> getMaxSizesInMb() {
    return maxSizesInMb;
  }

  public void setMaxSizesInMb(List<Long> maxSizesInMb) {
    this.maxSizesInMb = maxSizesInMb;
  }

  public EnvironmentDatabaseSchemaScalingOptionDTO performance(EnvironmentDatabaseSchemaPerformanceDTO performance) {
    this.performance = performance;
    return this;
  }

   /**
   * Get performance
   * @return performance
  **/
  @Schema(description = "")
  public EnvironmentDatabaseSchemaPerformanceDTO getPerformance() {
    return performance;
  }

  public void setPerformance(EnvironmentDatabaseSchemaPerformanceDTO performance) {
    this.performance = performance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnvironmentDatabaseSchemaScalingOptionDTO environmentDatabaseSchemaScalingOptionDTO = (EnvironmentDatabaseSchemaScalingOptionDTO) o;
    return Objects.equals(this.maxSizesInMb, environmentDatabaseSchemaScalingOptionDTO.maxSizesInMb) &&
        Objects.equals(this.performance, environmentDatabaseSchemaScalingOptionDTO.performance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxSizesInMb, performance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnvironmentDatabaseSchemaScalingOptionDTO {\n");
    
    sb.append("    maxSizesInMb: ").append(toIndentedString(maxSizesInMb)).append("\n");
    sb.append("    performance: ").append(toIndentedString(performance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
