/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.cx.commercecloud.management.openapi.model.EnvironmentDatabaseSchemaScalingDetailDTO;
import com.sap.cx.commercecloud.management.openapi.model.EnvironmentKubernetesClusterScalingDetailDTO;
import com.sap.cx.commercecloud.management.openapi.model.EnvironmentServiceScalingDetailDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Environment scaling details
 */
@Schema(description = "Environment scaling details")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class EnvironmentScalingDetailDTO {
  @SerializedName("subscriptionCode")
  private String subscriptionCode = null;

  @SerializedName("environmentCode")
  private String environmentCode = null;

  @SerializedName("hibernated")
  private Boolean hibernated = null;

  @SerializedName("kubernetesClusters")
  private List<EnvironmentKubernetesClusterScalingDetailDTO> kubernetesClusters = null;

  @SerializedName("databaseSchemas")
  private List<EnvironmentDatabaseSchemaScalingDetailDTO> databaseSchemas = null;

  @SerializedName("services")
  private List<EnvironmentServiceScalingDetailDTO> services = null;

  public EnvironmentScalingDetailDTO subscriptionCode(String subscriptionCode) {
    this.subscriptionCode = subscriptionCode;
    return this;
  }

   /**
   * subscriptionCode
   * @return subscriptionCode
  **/
  @Schema(required = true, description = "subscriptionCode")
  public String getSubscriptionCode() {
    return subscriptionCode;
  }

  public void setSubscriptionCode(String subscriptionCode) {
    this.subscriptionCode = subscriptionCode;
  }

  public EnvironmentScalingDetailDTO environmentCode(String environmentCode) {
    this.environmentCode = environmentCode;
    return this;
  }

   /**
   * environmentCode
   * @return environmentCode
  **/
  @Schema(required = true, description = "environmentCode")
  public String getEnvironmentCode() {
    return environmentCode;
  }

  public void setEnvironmentCode(String environmentCode) {
    this.environmentCode = environmentCode;
  }

  public EnvironmentScalingDetailDTO hibernated(Boolean hibernated) {
    this.hibernated = hibernated;
    return this;
  }

   /**
   * Indicates whether the environment is currently hibernated
   * @return hibernated
  **/
  @Schema(description = "Indicates whether the environment is currently hibernated")
  public Boolean isHibernated() {
    return hibernated;
  }

  public void setHibernated(Boolean hibernated) {
    this.hibernated = hibernated;
  }

  public EnvironmentScalingDetailDTO kubernetesClusters(List<EnvironmentKubernetesClusterScalingDetailDTO> kubernetesClusters) {
    this.kubernetesClusters = kubernetesClusters;
    return this;
  }

  public EnvironmentScalingDetailDTO addKubernetesClustersItem(EnvironmentKubernetesClusterScalingDetailDTO kubernetesClustersItem) {
    if (this.kubernetesClusters == null) {
      this.kubernetesClusters = new ArrayList<EnvironmentKubernetesClusterScalingDetailDTO>();
    }
    this.kubernetesClusters.add(kubernetesClustersItem);
    return this;
  }

   /**
   * kubernetesClusters
   * @return kubernetesClusters
  **/
  @Schema(description = "kubernetesClusters")
  public List<EnvironmentKubernetesClusterScalingDetailDTO> getKubernetesClusters() {
    return kubernetesClusters;
  }

  public void setKubernetesClusters(List<EnvironmentKubernetesClusterScalingDetailDTO> kubernetesClusters) {
    this.kubernetesClusters = kubernetesClusters;
  }

  public EnvironmentScalingDetailDTO databaseSchemas(List<EnvironmentDatabaseSchemaScalingDetailDTO> databaseSchemas) {
    this.databaseSchemas = databaseSchemas;
    return this;
  }

  public EnvironmentScalingDetailDTO addDatabaseSchemasItem(EnvironmentDatabaseSchemaScalingDetailDTO databaseSchemasItem) {
    if (this.databaseSchemas == null) {
      this.databaseSchemas = new ArrayList<EnvironmentDatabaseSchemaScalingDetailDTO>();
    }
    this.databaseSchemas.add(databaseSchemasItem);
    return this;
  }

   /**
   * databaseSchemas
   * @return databaseSchemas
  **/
  @Schema(description = "databaseSchemas")
  public List<EnvironmentDatabaseSchemaScalingDetailDTO> getDatabaseSchemas() {
    return databaseSchemas;
  }

  public void setDatabaseSchemas(List<EnvironmentDatabaseSchemaScalingDetailDTO> databaseSchemas) {
    this.databaseSchemas = databaseSchemas;
  }

  public EnvironmentScalingDetailDTO services(List<EnvironmentServiceScalingDetailDTO> services) {
    this.services = services;
    return this;
  }

  public EnvironmentScalingDetailDTO addServicesItem(EnvironmentServiceScalingDetailDTO servicesItem) {
    if (this.services == null) {
      this.services = new ArrayList<EnvironmentServiceScalingDetailDTO>();
    }
    this.services.add(servicesItem);
    return this;
  }

   /**
   * services
   * @return services
  **/
  @Schema(description = "services")
  public List<EnvironmentServiceScalingDetailDTO> getServices() {
    return services;
  }

  public void setServices(List<EnvironmentServiceScalingDetailDTO> services) {
    this.services = services;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnvironmentScalingDetailDTO environmentScalingDetailDTO = (EnvironmentScalingDetailDTO) o;
    return Objects.equals(this.subscriptionCode, environmentScalingDetailDTO.subscriptionCode) &&
        Objects.equals(this.environmentCode, environmentScalingDetailDTO.environmentCode) &&
        Objects.equals(this.hibernated, environmentScalingDetailDTO.hibernated) &&
        Objects.equals(this.kubernetesClusters, environmentScalingDetailDTO.kubernetesClusters) &&
        Objects.equals(this.databaseSchemas, environmentScalingDetailDTO.databaseSchemas) &&
        Objects.equals(this.services, environmentScalingDetailDTO.services);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subscriptionCode, environmentCode, hibernated, kubernetesClusters, databaseSchemas, services);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnvironmentScalingDetailDTO {\n");
    
    sb.append("    subscriptionCode: ").append(toIndentedString(subscriptionCode)).append("\n");
    sb.append("    environmentCode: ").append(toIndentedString(environmentCode)).append("\n");
    sb.append("    hibernated: ").append(toIndentedString(hibernated)).append("\n");
    sb.append("    kubernetesClusters: ").append(toIndentedString(kubernetesClusters)).append("\n");
    sb.append("    databaseSchemas: ").append(toIndentedString(databaseSchemas)).append("\n");
    sb.append("    services: ").append(toIndentedString(services)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
