/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Service autoscaling
 */
@Schema(description = "Service autoscaling")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class EnvironmentServiceAutoscalingConfigurationDTO {
  @SerializedName("enabled")
  private Boolean enabled = false;

  @SerializedName("minReplicas")
  private Integer minReplicas = null;

  @SerializedName("maxReplicas")
  private Integer maxReplicas = null;

  public EnvironmentServiceAutoscalingConfigurationDTO enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * enabled
   * @return enabled
  **/
  @Schema(required = true, description = "enabled")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public EnvironmentServiceAutoscalingConfigurationDTO minReplicas(Integer minReplicas) {
    this.minReplicas = minReplicas;
    return this;
  }

   /**
   * minReplicas
   * @return minReplicas
  **/
  @Schema(description = "minReplicas")
  public Integer getMinReplicas() {
    return minReplicas;
  }

  public void setMinReplicas(Integer minReplicas) {
    this.minReplicas = minReplicas;
  }

  public EnvironmentServiceAutoscalingConfigurationDTO maxReplicas(Integer maxReplicas) {
    this.maxReplicas = maxReplicas;
    return this;
  }

   /**
   * maxReplicas
   * @return maxReplicas
  **/
  @Schema(description = "maxReplicas")
  public Integer getMaxReplicas() {
    return maxReplicas;
  }

  public void setMaxReplicas(Integer maxReplicas) {
    this.maxReplicas = maxReplicas;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnvironmentServiceAutoscalingConfigurationDTO environmentServiceAutoscalingConfigurationDTO = (EnvironmentServiceAutoscalingConfigurationDTO) o;
    return Objects.equals(this.enabled, environmentServiceAutoscalingConfigurationDTO.enabled) &&
        Objects.equals(this.minReplicas, environmentServiceAutoscalingConfigurationDTO.minReplicas) &&
        Objects.equals(this.maxReplicas, environmentServiceAutoscalingConfigurationDTO.maxReplicas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, minReplicas, maxReplicas);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnvironmentServiceAutoscalingConfigurationDTO {\n");
    
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    minReplicas: ").append(toIndentedString(minReplicas)).append("\n");
    sb.append("    maxReplicas: ").append(toIndentedString(maxReplicas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
