/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Read only view of the BillingConfiguration of given Environment. Only used in get requests, not for updating the data
 */
@Schema(description = "Read only view of the BillingConfiguration of given Environment. Only used in get requests, not for updating the data")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class EnvironmentBillingConfigurationDTO {
  @SerializedName("active")
  private Boolean active = false;

  @SerializedName("enabled")
  private Boolean enabled = false;

  @SerializedName("sapProductNumber")
  private String sapProductNumber = null;

  @SerializedName("crmTenantId")
  private String crmTenantId = null;

  @SerializedName("dataStream")
  private String dataStream = null;

  @SerializedName("tenant")
  private String tenant = null;

  public EnvironmentBillingConfigurationDTO active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Describes if the BillingConfiguration is active
   * @return active
  **/
  @Schema(description = "Describes if the BillingConfiguration is active")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public EnvironmentBillingConfigurationDTO enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Describes if the BillingConfiguration is enabled
   * @return enabled
  **/
  @Schema(description = "Describes if the BillingConfiguration is enabled")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public EnvironmentBillingConfigurationDTO sapProductNumber(String sapProductNumber) {
    this.sapProductNumber = sapProductNumber;
    return this;
  }

   /**
   * SAP Product Number
   * @return sapProductNumber
  **/
  @Schema(description = "SAP Product Number")
  public String getSapProductNumber() {
    return sapProductNumber;
  }

  public void setSapProductNumber(String sapProductNumber) {
    this.sapProductNumber = sapProductNumber;
  }

  public EnvironmentBillingConfigurationDTO crmTenantId(String crmTenantId) {
    this.crmTenantId = crmTenantId;
    return this;
  }

   /**
   * SAP CRM tenant ID
   * @return crmTenantId
  **/
  @Schema(description = "SAP CRM tenant ID")
  public String getCrmTenantId() {
    return crmTenantId;
  }

  public void setCrmTenantId(String crmTenantId) {
    this.crmTenantId = crmTenantId;
  }

  public EnvironmentBillingConfigurationDTO dataStream(String dataStream) {
    this.dataStream = dataStream;
    return this;
  }

   /**
   * DataStream name
   * @return dataStream
  **/
  @Schema(description = "DataStream name")
  public String getDataStream() {
    return dataStream;
  }

  public void setDataStream(String dataStream) {
    this.dataStream = dataStream;
  }

  public EnvironmentBillingConfigurationDTO tenant(String tenant) {
    this.tenant = tenant;
    return this;
  }

   /**
   * Tenant name
   * @return tenant
  **/
  @Schema(description = "Tenant name")
  public String getTenant() {
    return tenant;
  }

  public void setTenant(String tenant) {
    this.tenant = tenant;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnvironmentBillingConfigurationDTO environmentBillingConfigurationDTO = (EnvironmentBillingConfigurationDTO) o;
    return Objects.equals(this.active, environmentBillingConfigurationDTO.active) &&
        Objects.equals(this.enabled, environmentBillingConfigurationDTO.enabled) &&
        Objects.equals(this.sapProductNumber, environmentBillingConfigurationDTO.sapProductNumber) &&
        Objects.equals(this.crmTenantId, environmentBillingConfigurationDTO.crmTenantId) &&
        Objects.equals(this.dataStream, environmentBillingConfigurationDTO.dataStream) &&
        Objects.equals(this.tenant, environmentBillingConfigurationDTO.tenant);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, enabled, sapProductNumber, crmTenantId, dataStream, tenant);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnvironmentBillingConfigurationDTO {\n");
    
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    sapProductNumber: ").append(toIndentedString(sapProductNumber)).append("\n");
    sb.append("    crmTenantId: ").append(toIndentedString(crmTenantId)).append("\n");
    sb.append("    dataStream: ").append(toIndentedString(dataStream)).append("\n");
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
