/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.cx.commercecloud.management.openapi.model.EnvironmentKubernetesClusterScalingOptionDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Kubernetes cluster scaling options
 */
@Schema(description = "Kubernetes cluster scaling options")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class EnvironmentKubernetesClusterScalingOptionsDTO {
  @SerializedName("code")
  private String code = null;

  @SerializedName("options")
  private List<EnvironmentKubernetesClusterScalingOptionDTO> options = null;

  public EnvironmentKubernetesClusterScalingOptionsDTO code(String code) {
    this.code = code;
    return this;
  }

   /**
   * code
   * @return code
  **/
  @Schema(required = true, description = "code")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public EnvironmentKubernetesClusterScalingOptionsDTO options(List<EnvironmentKubernetesClusterScalingOptionDTO> options) {
    this.options = options;
    return this;
  }

  public EnvironmentKubernetesClusterScalingOptionsDTO addOptionsItem(EnvironmentKubernetesClusterScalingOptionDTO optionsItem) {
    if (this.options == null) {
      this.options = new ArrayList<EnvironmentKubernetesClusterScalingOptionDTO>();
    }
    this.options.add(optionsItem);
    return this;
  }

   /**
   * options
   * @return options
  **/
  @Schema(description = "options")
  public List<EnvironmentKubernetesClusterScalingOptionDTO> getOptions() {
    return options;
  }

  public void setOptions(List<EnvironmentKubernetesClusterScalingOptionDTO> options) {
    this.options = options;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnvironmentKubernetesClusterScalingOptionsDTO environmentKubernetesClusterScalingOptionsDTO = (EnvironmentKubernetesClusterScalingOptionsDTO) o;
    return Objects.equals(this.code, environmentKubernetesClusterScalingOptionsDTO.code) &&
        Objects.equals(this.options, environmentKubernetesClusterScalingOptionsDTO.options);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, options);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnvironmentKubernetesClusterScalingOptionsDTO {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
