/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Problem detail message (https://tools.ietf.org/html/rfc7807)
 */
@Schema(description = "Problem detail message (https://tools.ietf.org/html/rfc7807)")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T21:55:47.726988+02:00[Europe/Rome]")

public class ErrorDTO {
    @SerializedName("title")
    private String title = null;

    @SerializedName("detail")
    private String detail = null;

    /**
     * Human-readable summary of the problem type
     *
     * @return title
     **/
    @Schema(description = "Human-readable summary of the problem type")
    public String getTitle() {
        return title;
    }

    /**
     * Human-readable explanation specific to this occurrence of the problem
     *
     * @return detail
     **/
    @Schema(description = "Human-readable explanation specific to this occurrence of the problem")
    public String getDetail() {
        return detail;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ErrorDTO errorDTO = (ErrorDTO) o;
        return Objects.equals(this.title, errorDTO.title) && Objects.equals(this.detail, errorDTO.detail);
    }

    @Override
    public int hashCode() {
        return Objects.hash(title, detail);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ErrorDTO {\n");

        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
