/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * RateLimitingDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class RateLimitingDTO {
  @SerializedName("threshold")
  private Integer threshold = null;

  @SerializedName("cooldownTimeInSeconds")
  private Integer cooldownTimeInSeconds = null;

  public RateLimitingDTO threshold(Integer threshold) {
    this.threshold = threshold;
    return this;
  }

   /**
   * Maximum allowed number of connections from a single IP address before throttling
   * @return threshold
  **/
  @Schema(description = "Maximum allowed number of connections from a single IP address before throttling")
  public Integer getThreshold() {
    return threshold;
  }

  public void setThreshold(Integer threshold) {
    this.threshold = threshold;
  }

  public RateLimitingDTO cooldownTimeInSeconds(Integer cooldownTimeInSeconds) {
    this.cooldownTimeInSeconds = cooldownTimeInSeconds;
    return this;
  }

   /**
   * Time period in seconds before the rate limit is reset
   * @return cooldownTimeInSeconds
  **/
  @Schema(description = "Time period in seconds before the rate limit is reset")
  public Integer getCooldownTimeInSeconds() {
    return cooldownTimeInSeconds;
  }

  public void setCooldownTimeInSeconds(Integer cooldownTimeInSeconds) {
    this.cooldownTimeInSeconds = cooldownTimeInSeconds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RateLimitingDTO rateLimitingDTO = (RateLimitingDTO) o;
    return Objects.equals(this.threshold, rateLimitingDTO.threshold) &&
        Objects.equals(this.cooldownTimeInSeconds, rateLimitingDTO.cooldownTimeInSeconds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(threshold, cooldownTimeInSeconds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RateLimitingDTO {\n");
    
    sb.append("    threshold: ").append(toIndentedString(threshold)).append("\n");
    sb.append("    cooldownTimeInSeconds: ").append(toIndentedString(cooldownTimeInSeconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
