/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * Details of a scheduled activity
 */
@Schema(description = "Details of a scheduled activity")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class ScheduledActivityDetailDTO {
  @SerializedName("code")
  private String code = null;

  @SerializedName("subscriptionCode")
  private String subscriptionCode = null;

  @SerializedName("environmentCode")
  private String environmentCode = null;

  @SerializedName("activityType")
  private String activityType = null;

  @SerializedName("scheduledTimestamp")
  private OffsetDateTime scheduledTimestamp = null;

  @SerializedName("startedTimestamp")
  private OffsetDateTime startedTimestamp = null;

  @SerializedName("finishedTimestamp")
  private OffsetDateTime finishedTimestamp = null;

  /**
   * Status of the scheduled activity
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    @SerializedName("SCHEDULED")
    SCHEDULED("SCHEDULED"),
    @SerializedName("QUEUED")
    QUEUED("QUEUED"),
    @SerializedName("QUEUED_AWAITING_LOCK")
    QUEUED_AWAITING_LOCK("QUEUED_AWAITING_LOCK"),
    @SerializedName("RUNNING")
    RUNNING("RUNNING"),
    @SerializedName("SUCCESS")
    SUCCESS("SUCCESS"),
    @SerializedName("ERROR")
    ERROR("ERROR"),
    @SerializedName("CANCELING")
    CANCELING("CANCELING"),
    @SerializedName("CANCELED")
    CANCELED("CANCELED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return StatusEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("readOnly")
  private Boolean readOnly = null;

  @SerializedName("updatable")
  private Boolean updatable = null;

  @SerializedName("cancelable")
  private Boolean cancelable = null;

  @SerializedName("createdBy")
  private String createdBy = null;

  @SerializedName("createdTimestamp")
  private OffsetDateTime createdTimestamp = null;

  @SerializedName("lastModifiedBy")
  private String lastModifiedBy = null;

  @SerializedName("lastModifiedTimestamp")
  private OffsetDateTime lastModifiedTimestamp = null;

  @SerializedName("activityName")
  private String activityName = null;

  @SerializedName("activityNotes")
  private String activityNotes = null;

  @SerializedName("activityImpactNotes")
  private String activityImpactNotes = null;

  public ScheduledActivityDetailDTO code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Scheduled activity code
   * @return code
  **/
  @Schema(required = true, description = "Scheduled activity code")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public ScheduledActivityDetailDTO subscriptionCode(String subscriptionCode) {
    this.subscriptionCode = subscriptionCode;
    return this;
  }

   /**
   * Code of the subscription
   * @return subscriptionCode
  **/
  @Schema(required = true, description = "Code of the subscription")
  public String getSubscriptionCode() {
    return subscriptionCode;
  }

  public void setSubscriptionCode(String subscriptionCode) {
    this.subscriptionCode = subscriptionCode;
  }

  public ScheduledActivityDetailDTO environmentCode(String environmentCode) {
    this.environmentCode = environmentCode;
    return this;
  }

   /**
   * Code of the environment for which the activity is scheduled for
   * @return environmentCode
  **/
  @Schema(required = true, description = "Code of the environment for which the activity is scheduled for")
  public String getEnvironmentCode() {
    return environmentCode;
  }

  public void setEnvironmentCode(String environmentCode) {
    this.environmentCode = environmentCode;
  }

  public ScheduledActivityDetailDTO activityType(String activityType) {
    this.activityType = activityType;
    return this;
  }

   /**
   * Type of activity
   * @return activityType
  **/
  @Schema(required = true, description = "Type of activity")
  public String getActivityType() {
    return activityType;
  }

  public void setActivityType(String activityType) {
    this.activityType = activityType;
  }

  public ScheduledActivityDetailDTO scheduledTimestamp(OffsetDateTime scheduledTimestamp) {
    this.scheduledTimestamp = scheduledTimestamp;
    return this;
  }

   /**
   * Time the activity is scheduled for.
   * @return scheduledTimestamp
  **/
  @Schema(required = true, description = "Time the activity is scheduled for.")
  public OffsetDateTime getScheduledTimestamp() {
    return scheduledTimestamp;
  }

  public void setScheduledTimestamp(OffsetDateTime scheduledTimestamp) {
    this.scheduledTimestamp = scheduledTimestamp;
  }

  public ScheduledActivityDetailDTO startedTimestamp(OffsetDateTime startedTimestamp) {
    this.startedTimestamp = startedTimestamp;
    return this;
  }

   /**
   * Time the scheduled activity was started
   * @return startedTimestamp
  **/
  @Schema(description = "Time the scheduled activity was started")
  public OffsetDateTime getStartedTimestamp() {
    return startedTimestamp;
  }

  public void setStartedTimestamp(OffsetDateTime startedTimestamp) {
    this.startedTimestamp = startedTimestamp;
  }

  public ScheduledActivityDetailDTO finishedTimestamp(OffsetDateTime finishedTimestamp) {
    this.finishedTimestamp = finishedTimestamp;
    return this;
  }

   /**
   * Time the scheduled activity was finished
   * @return finishedTimestamp
  **/
  @Schema(description = "Time the scheduled activity was finished")
  public OffsetDateTime getFinishedTimestamp() {
    return finishedTimestamp;
  }

  public void setFinishedTimestamp(OffsetDateTime finishedTimestamp) {
    this.finishedTimestamp = finishedTimestamp;
  }

  public ScheduledActivityDetailDTO status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Status of the scheduled activity
   * @return status
  **/
  @Schema(required = true, description = "Status of the scheduled activity")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public ScheduledActivityDetailDTO readOnly(Boolean readOnly) {
    this.readOnly = readOnly;
    return this;
  }

   /**
   * Describes if the scheduled activity is editable or read-only
   * @return readOnly
  **/
  @Schema(description = "Describes if the scheduled activity is editable or read-only")
  public Boolean isReadOnly() {
    return readOnly;
  }

  public void setReadOnly(Boolean readOnly) {
    this.readOnly = readOnly;
  }

  public ScheduledActivityDetailDTO updatable(Boolean updatable) {
    this.updatable = updatable;
    return this;
  }

   /**
   * Describes if the scheduled activity is updatable/re-schedulable by the user
   * @return updatable
  **/
  @Schema(description = "Describes if the scheduled activity is updatable/re-schedulable by the user")
  public Boolean isUpdatable() {
    return updatable;
  }

  public void setUpdatable(Boolean updatable) {
    this.updatable = updatable;
  }

  public ScheduledActivityDetailDTO cancelable(Boolean cancelable) {
    this.cancelable = cancelable;
    return this;
  }

   /**
   * Describes if the scheduled activity is cancelable by the user
   * @return cancelable
  **/
  @Schema(description = "Describes if the scheduled activity is cancelable by the user")
  public Boolean isCancelable() {
    return cancelable;
  }

  public void setCancelable(Boolean cancelable) {
    this.cancelable = cancelable;
  }

  public ScheduledActivityDetailDTO createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * User that created the scheduled activity
   * @return createdBy
  **/
  @Schema(description = "User that created the scheduled activity")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public ScheduledActivityDetailDTO createdTimestamp(OffsetDateTime createdTimestamp) {
    this.createdTimestamp = createdTimestamp;
    return this;
  }

   /**
   * Scheduled activity creation timestamp
   * @return createdTimestamp
  **/
  @Schema(description = "Scheduled activity creation timestamp")
  public OffsetDateTime getCreatedTimestamp() {
    return createdTimestamp;
  }

  public void setCreatedTimestamp(OffsetDateTime createdTimestamp) {
    this.createdTimestamp = createdTimestamp;
  }

  public ScheduledActivityDetailDTO lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Last user that modified the scheduled activity
   * @return lastModifiedBy
  **/
  @Schema(description = "Last user that modified the scheduled activity")
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public ScheduledActivityDetailDTO lastModifiedTimestamp(OffsetDateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
    return this;
  }

   /**
   * Last time the scheduled activity was modified
   * @return lastModifiedTimestamp
  **/
  @Schema(description = "Last time the scheduled activity was modified")
  public OffsetDateTime getLastModifiedTimestamp() {
    return lastModifiedTimestamp;
  }

  public void setLastModifiedTimestamp(OffsetDateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
  }

  public ScheduledActivityDetailDTO activityName(String activityName) {
    this.activityName = activityName;
    return this;
  }

   /**
   * Name of the scheduled activity
   * @return activityName
  **/
  @Schema(description = "Name of the scheduled activity")
  public String getActivityName() {
    return activityName;
  }

  public void setActivityName(String activityName) {
    this.activityName = activityName;
  }

  public ScheduledActivityDetailDTO activityNotes(String activityNotes) {
    this.activityNotes = activityNotes;
    return this;
  }

   /**
   * Notes for the scheduled activity
   * @return activityNotes
  **/
  @Schema(description = "Notes for the scheduled activity")
  public String getActivityNotes() {
    return activityNotes;
  }

  public void setActivityNotes(String activityNotes) {
    this.activityNotes = activityNotes;
  }

  public ScheduledActivityDetailDTO activityImpactNotes(String activityImpactNotes) {
    this.activityImpactNotes = activityImpactNotes;
    return this;
  }

   /**
   * Impact notes for the scheduled activity
   * @return activityImpactNotes
  **/
  @Schema(description = "Impact notes for the scheduled activity")
  public String getActivityImpactNotes() {
    return activityImpactNotes;
  }

  public void setActivityImpactNotes(String activityImpactNotes) {
    this.activityImpactNotes = activityImpactNotes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScheduledActivityDetailDTO scheduledActivityDetailDTO = (ScheduledActivityDetailDTO) o;
    return Objects.equals(this.code, scheduledActivityDetailDTO.code) &&
        Objects.equals(this.subscriptionCode, scheduledActivityDetailDTO.subscriptionCode) &&
        Objects.equals(this.environmentCode, scheduledActivityDetailDTO.environmentCode) &&
        Objects.equals(this.activityType, scheduledActivityDetailDTO.activityType) &&
        Objects.equals(this.scheduledTimestamp, scheduledActivityDetailDTO.scheduledTimestamp) &&
        Objects.equals(this.startedTimestamp, scheduledActivityDetailDTO.startedTimestamp) &&
        Objects.equals(this.finishedTimestamp, scheduledActivityDetailDTO.finishedTimestamp) &&
        Objects.equals(this.status, scheduledActivityDetailDTO.status) &&
        Objects.equals(this.readOnly, scheduledActivityDetailDTO.readOnly) &&
        Objects.equals(this.updatable, scheduledActivityDetailDTO.updatable) &&
        Objects.equals(this.cancelable, scheduledActivityDetailDTO.cancelable) &&
        Objects.equals(this.createdBy, scheduledActivityDetailDTO.createdBy) &&
        Objects.equals(this.createdTimestamp, scheduledActivityDetailDTO.createdTimestamp) &&
        Objects.equals(this.lastModifiedBy, scheduledActivityDetailDTO.lastModifiedBy) &&
        Objects.equals(this.lastModifiedTimestamp, scheduledActivityDetailDTO.lastModifiedTimestamp) &&
        Objects.equals(this.activityName, scheduledActivityDetailDTO.activityName) &&
        Objects.equals(this.activityNotes, scheduledActivityDetailDTO.activityNotes) &&
        Objects.equals(this.activityImpactNotes, scheduledActivityDetailDTO.activityImpactNotes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, subscriptionCode, environmentCode, activityType, scheduledTimestamp, startedTimestamp, finishedTimestamp, status, readOnly, updatable, cancelable, createdBy, createdTimestamp, lastModifiedBy, lastModifiedTimestamp, activityName, activityNotes, activityImpactNotes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScheduledActivityDetailDTO {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    subscriptionCode: ").append(toIndentedString(subscriptionCode)).append("\n");
    sb.append("    environmentCode: ").append(toIndentedString(environmentCode)).append("\n");
    sb.append("    activityType: ").append(toIndentedString(activityType)).append("\n");
    sb.append("    scheduledTimestamp: ").append(toIndentedString(scheduledTimestamp)).append("\n");
    sb.append("    startedTimestamp: ").append(toIndentedString(startedTimestamp)).append("\n");
    sb.append("    finishedTimestamp: ").append(toIndentedString(finishedTimestamp)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
    sb.append("    updatable: ").append(toIndentedString(updatable)).append("\n");
    sb.append("    cancelable: ").append(toIndentedString(cancelable)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdTimestamp: ").append(toIndentedString(createdTimestamp)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedTimestamp: ").append(toIndentedString(lastModifiedTimestamp)).append("\n");
    sb.append("    activityName: ").append(toIndentedString(activityName)).append("\n");
    sb.append("    activityNotes: ").append(toIndentedString(activityNotes)).append("\n");
    sb.append("    activityImpactNotes: ").append(toIndentedString(activityImpactNotes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
