/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Entity to represent a property used by a service into an environment
 */
@Schema(description = "Entity to represent a property used by a service into an environment")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T21:55:47.726988+02:00[Europe/Rome]")

public class ServicePropertyDTO {
    @SerializedName("key")
    private String key = null;

    @SerializedName("value")
    private Object value = null;

    @SerializedName("flags")
    private List<String> flags = null;

    public ServicePropertyDTO key(String key) {
        this.key = key;
        return this;
    }

    /**
     * Property name
     *
     * @return key
     **/
    @Schema(required = true, description = "Property name")
    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public ServicePropertyDTO value(Object value) {
        this.value = value;
        return this;
    }

    /**
     * Property value
     *
     * @return value
     **/
    @Schema(required = true, description = "Property value")
    public Object getValue() {
        return value;
    }

    public void setValue(Object value) {
        this.value = value;
    }

    public ServicePropertyDTO flags(List<String> flags) {
        this.flags = flags;
        return this;
    }

    public ServicePropertyDTO addFlagsItem(String flagsItem) {
        if (this.flags == null) {
            this.flags = new ArrayList<String>();
        }
        this.flags.add(flagsItem);
        return this;
    }

    /**
     * Array of build details
     *
     * @return flags
     **/
    @Schema(description = "Array of build details")
    public List<String> getFlags() {
        return flags;
    }

    public void setFlags(List<String> flags) {
        this.flags = flags;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ServicePropertyDTO servicePropertyDTO = (ServicePropertyDTO) o;
        return Objects.equals(this.key, servicePropertyDTO.key) && Objects.equals(this.value, servicePropertyDTO.value) && Objects.equals(this.flags, servicePropertyDTO.flags);
    }

    @Override
    public int hashCode() {
        return Objects.hash(key, value, flags);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ServicePropertyDTO {\n");

        sb.append("    key: ").append(toIndentedString(key)).append("\n");
        sb.append("    value: ").append(toIndentedString(value)).append("\n");
        sb.append("    flags: ").append(toIndentedString(flags)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
