/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Reference to an endpoint
 */
@Schema(description = "Reference to an endpoint")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class SslCertificateEndpointReferenceDTO {
  @SerializedName("code")
  private String code = null;

  @SerializedName("environmentCode")
  private String environmentCode = null;

  @SerializedName("environmentName")
  private String environmentName = null;

  @SerializedName("name")
  private String name = null;

  public SslCertificateEndpointReferenceDTO code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Endpoint code
   * @return code
  **/
  @Schema(description = "Endpoint code")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public SslCertificateEndpointReferenceDTO environmentCode(String environmentCode) {
    this.environmentCode = environmentCode;
    return this;
  }

   /**
   * Environment code
   * @return environmentCode
  **/
  @Schema(description = "Environment code")
  public String getEnvironmentCode() {
    return environmentCode;
  }

  public void setEnvironmentCode(String environmentCode) {
    this.environmentCode = environmentCode;
  }

  public SslCertificateEndpointReferenceDTO environmentName(String environmentName) {
    this.environmentName = environmentName;
    return this;
  }

   /**
   * Environment name
   * @return environmentName
  **/
  @Schema(description = "Environment name")
  public String getEnvironmentName() {
    return environmentName;
  }

  public void setEnvironmentName(String environmentName) {
    this.environmentName = environmentName;
  }

  public SslCertificateEndpointReferenceDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Endpoint name
   * @return name
  **/
  @Schema(description = "Endpoint name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SslCertificateEndpointReferenceDTO sslCertificateEndpointReferenceDTO = (SslCertificateEndpointReferenceDTO) o;
    return Objects.equals(this.code, sslCertificateEndpointReferenceDTO.code) &&
        Objects.equals(this.environmentCode, sslCertificateEndpointReferenceDTO.environmentCode) &&
        Objects.equals(this.environmentName, sslCertificateEndpointReferenceDTO.environmentName) &&
        Objects.equals(this.name, sslCertificateEndpointReferenceDTO.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, environmentCode, environmentName, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SslCertificateEndpointReferenceDTO {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    environmentCode: ").append(toIndentedString(environmentCode)).append("\n");
    sb.append("    environmentName: ").append(toIndentedString(environmentName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
