/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.cx.commercecloud.management.openapi.model.SslCertificateEndpointReferenceDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * SSL certificate details
 */
@Schema(description = "SSL certificate details")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class SslCertificateDTO {
  @SerializedName("code")
  private String code = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("subscriptionCode")
  private String subscriptionCode = null;

  @SerializedName("domains")
  private List<String> domains = new ArrayList<String>();

  @SerializedName("issuer")
  private String issuer = null;

  @SerializedName("expirationDate")
  private OffsetDateTime expirationDate = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("endpoints")
  private List<SslCertificateEndpointReferenceDTO> endpoints = null;

  public SslCertificateDTO code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Certificate code
   * @return code
  **/
  @Schema(required = true, description = "Certificate code")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public SslCertificateDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Certificate name
   * @return name
  **/
  @Schema(required = true, description = "Certificate name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SslCertificateDTO subscriptionCode(String subscriptionCode) {
    this.subscriptionCode = subscriptionCode;
    return this;
  }

   /**
   * Code of the subscription
   * @return subscriptionCode
  **/
  @Schema(required = true, description = "Code of the subscription")
  public String getSubscriptionCode() {
    return subscriptionCode;
  }

  public void setSubscriptionCode(String subscriptionCode) {
    this.subscriptionCode = subscriptionCode;
  }

  public SslCertificateDTO domains(List<String> domains) {
    this.domains = domains;
    return this;
  }

  public SslCertificateDTO addDomainsItem(String domainsItem) {
    this.domains.add(domainsItem);
    return this;
  }

   /**
   * A list of the domains associated with this certificate
   * @return domains
  **/
  @Schema(required = true, description = "A list of the domains associated with this certificate")
  public List<String> getDomains() {
    return domains;
  }

  public void setDomains(List<String> domains) {
    this.domains = domains;
  }

  public SslCertificateDTO issuer(String issuer) {
    this.issuer = issuer;
    return this;
  }

   /**
   * SSL certificate issuer
   * @return issuer
  **/
  @Schema(required = true, description = "SSL certificate issuer")
  public String getIssuer() {
    return issuer;
  }

  public void setIssuer(String issuer) {
    this.issuer = issuer;
  }

  public SslCertificateDTO expirationDate(OffsetDateTime expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * The Expiration Date of the certificate.
   * @return expirationDate
  **/
  @Schema(example = "2017-07-21T17:32:28Z", required = true, description = "The Expiration Date of the certificate.")
  public OffsetDateTime getExpirationDate() {
    return expirationDate;
  }

  public void setExpirationDate(OffsetDateTime expirationDate) {
    this.expirationDate = expirationDate;
  }

  public SslCertificateDTO description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public SslCertificateDTO endpoints(List<SslCertificateEndpointReferenceDTO> endpoints) {
    this.endpoints = endpoints;
    return this;
  }

  public SslCertificateDTO addEndpointsItem(SslCertificateEndpointReferenceDTO endpointsItem) {
    if (this.endpoints == null) {
      this.endpoints = new ArrayList<SslCertificateEndpointReferenceDTO>();
    }
    this.endpoints.add(endpointsItem);
    return this;
  }

   /**
   * All endpoints, in which this certificate is used.
   * @return endpoints
  **/
  @Schema(description = "All endpoints, in which this certificate is used.")
  public List<SslCertificateEndpointReferenceDTO> getEndpoints() {
    return endpoints;
  }

  public void setEndpoints(List<SslCertificateEndpointReferenceDTO> endpoints) {
    this.endpoints = endpoints;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SslCertificateDTO sslCertificateDTO = (SslCertificateDTO) o;
    return Objects.equals(this.code, sslCertificateDTO.code) &&
        Objects.equals(this.name, sslCertificateDTO.name) &&
        Objects.equals(this.subscriptionCode, sslCertificateDTO.subscriptionCode) &&
        Objects.equals(this.domains, sslCertificateDTO.domains) &&
        Objects.equals(this.issuer, sslCertificateDTO.issuer) &&
        Objects.equals(this.expirationDate, sslCertificateDTO.expirationDate) &&
        Objects.equals(this.description, sslCertificateDTO.description) &&
        Objects.equals(this.endpoints, sslCertificateDTO.endpoints);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, name, subscriptionCode, domains, issuer, expirationDate, description, endpoints);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SslCertificateDTO {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    subscriptionCode: ").append(toIndentedString(subscriptionCode)).append("\n");
    sb.append("    domains: ").append(toIndentedString(domains)).append("\n");
    sb.append("    issuer: ").append(toIndentedString(issuer)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    endpoints: ").append(toIndentedString(endpoints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
