/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.cx.commercecloud.management.openapi.model.SslCertificateDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Collection of SSL certificates
 */
@Schema(description = "Collection of SSL certificates")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class SslCertificatesDTO {
  @SerializedName("value")
  private List<SslCertificateDTO> value = null;

  @SerializedName("count")
  private Integer count = null;

  public SslCertificatesDTO value(List<SslCertificateDTO> value) {
    this.value = value;
    return this;
  }

  public SslCertificatesDTO addValueItem(SslCertificateDTO valueItem) {
    if (this.value == null) {
      this.value = new ArrayList<SslCertificateDTO>();
    }
    this.value.add(valueItem);
    return this;
  }

   /**
   * Array of SSL certificates
   * @return value
  **/
  @Schema(description = "Array of SSL certificates")
  public List<SslCertificateDTO> getValue() {
    return value;
  }

  public void setValue(List<SslCertificateDTO> value) {
    this.value = value;
  }

  public SslCertificatesDTO count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * The total number of SSL certificates
   * @return count
  **/
  @Schema(description = "The total number of SSL certificates")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SslCertificatesDTO sslCertificatesDTO = (SslCertificatesDTO) o;
    return Objects.equals(this.value, sslCertificatesDTO.value) &&
        Objects.equals(this.count, sslCertificatesDTO.count);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, count);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SslCertificatesDTO {\n");
    
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
