/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Traffic Split Audit History response DTO.
 */
@Schema(description = "Traffic Split Audit History response DTO.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T21:55:47.726988+02:00[Europe/Rome]")

public class TrafficSplitHistoryListDTO {
    @SerializedName("value")
    private List<TrafficSplitDetailDTO> value = null;

    @SerializedName("count")
    private Integer count = null;

    public TrafficSplitHistoryListDTO value(List<TrafficSplitDetailDTO> value) {
        this.value = value;
        return this;
    }

    public TrafficSplitHistoryListDTO addValueItem(TrafficSplitDetailDTO valueItem) {
        if (this.value == null) {
            this.value = new ArrayList<TrafficSplitDetailDTO>();
        }
        this.value.add(valueItem);
        return this;
    }

    /**
     * Array of traffic split history detail
     *
     * @return value
     **/
    @Schema(description = "Array of traffic split history detail")
    public List<TrafficSplitDetailDTO> getValue() {
        return value;
    }

    public void setValue(List<TrafficSplitDetailDTO> value) {
        this.value = value;
    }

    public TrafficSplitHistoryListDTO count(Integer count) {
        this.count = count;
        return this;
    }

    /**
     * The total number of traffic split
     *
     * @return count
     **/
    @Schema(description = "The total number of traffic split")
    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TrafficSplitHistoryListDTO trafficSplitHistoryListDTO = (TrafficSplitHistoryListDTO) o;
        return Objects.equals(this.value, trafficSplitHistoryListDTO.value) && Objects.equals(this.count, trafficSplitHistoryListDTO.count);
    }

    @Override
    public int hashCode() {
        return Objects.hash(value, count);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TrafficSplitHistoryListDTO {\n");

        sb.append("    value: ").append(toIndentedString(value)).append("\n");
        sb.append("    count: ").append(toIndentedString(count)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
