/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Traffic percentage Request DTO.
 */
@Schema(description = "Traffic percentage Request DTO.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T21:55:47.726988+02:00[Europe/Rome]")

public class TrafficPercentageRequestDTO {
    @SerializedName("code")
    private String code = null;

    @SerializedName("percentage")
    private Integer percentage = null;

    public TrafficPercentageRequestDTO code(String code) {
        this.code = code;
        return this;
    }

    /**
     * Code of the traffic split entity. eg. service code, endpoint code
     *
     * @return code
     **/
    @Schema(required = true, description = "Code of the traffic split entity. eg. service code, endpoint code")
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public TrafficPercentageRequestDTO percentage(Integer percentage) {
        this.percentage = percentage;
        return this;
    }

    /**
     * Percentage of the traffic split
     * minimum: 0
     * maximum: 100
     *
     * @return percentage
     **/
    @Schema(required = true, description = "Percentage of the traffic split")
    public Integer getPercentage() {
        return percentage;
    }

    public void setPercentage(Integer percentage) {
        this.percentage = percentage;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TrafficPercentageRequestDTO trafficPercentageRequestDTO = (TrafficPercentageRequestDTO) o;
        return Objects.equals(this.code, trafficPercentageRequestDTO.code) && Objects.equals(this.percentage, trafficPercentageRequestDTO.percentage);
    }

    @Override
    public int hashCode() {
        return Objects.hash(code, percentage);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TrafficPercentageRequestDTO {\n");

        sb.append("    code: ").append(toIndentedString(code)).append("\n");
        sb.append("    percentage: ").append(toIndentedString(percentage)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
