/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * DTO to update a list of environments for a user role assignment
 */
@Schema(description = "DTO to update a list of environments for a user role assignment")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class UpdateUserRoleAssignmentDTO {
  @SerializedName("username")
  private String username = null;

  @SerializedName("role")
  private String role = null;

  @SerializedName("environments")
  private List<String> environments = new ArrayList<String>();

  public UpdateUserRoleAssignmentDTO username(String username) {
    this.username = username;
    return this;
  }

   /**
   * username
   * @return username
  **/
  @Schema(required = true, description = "username")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public UpdateUserRoleAssignmentDTO role(String role) {
    this.role = role;
    return this;
  }

   /**
   * role
   * @return role
  **/
  @Schema(required = true, description = "role")
  public String getRole() {
    return role;
  }

  public void setRole(String role) {
    this.role = role;
  }

  public UpdateUserRoleAssignmentDTO environments(List<String> environments) {
    this.environments = environments;
    return this;
  }

  public UpdateUserRoleAssignmentDTO addEnvironmentsItem(String environmentsItem) {
    this.environments.add(environmentsItem);
    return this;
  }

   /**
   * list of environments for the role
   * @return environments
  **/
  @Schema(required = true, description = "list of environments for the role")
  public List<String> getEnvironments() {
    return environments;
  }

  public void setEnvironments(List<String> environments) {
    this.environments = environments;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateUserRoleAssignmentDTO updateUserRoleAssignmentDTO = (UpdateUserRoleAssignmentDTO) o;
    return Objects.equals(this.username, updateUserRoleAssignmentDTO.username) &&
        Objects.equals(this.role, updateUserRoleAssignmentDTO.role) &&
        Objects.equals(this.environments, updateUserRoleAssignmentDTO.environments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(username, role, environments);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateUserRoleAssignmentDTO {\n");
    
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    environments: ").append(toIndentedString(environments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
