/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * Service update
 */
@Schema(description = "Service update")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class UpdateEnvironmentServiceScalingDetailDTO {
  @SerializedName("code")
  private String code = null;

  @SerializedName("replicas")
  private Integer replicas = null;

  @SerializedName("requestsCpu")
  private String requestsCpu = null;

  @SerializedName("noLimitsCpu")
  private Boolean noLimitsCpu = null;

  @SerializedName("requestsMemory")
  private String requestsMemory = null;

  @SerializedName("memoryScaleFactor")
  private BigDecimal memoryScaleFactor = null;

  @SerializedName("storageSize")
  private String storageSize = null;

  public UpdateEnvironmentServiceScalingDetailDTO code(String code) {
    this.code = code;
    return this;
  }

   /**
   * code
   * @return code
  **/
  @Schema(required = true, description = "code")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public UpdateEnvironmentServiceScalingDetailDTO replicas(Integer replicas) {
    this.replicas = replicas;
    return this;
  }

   /**
   * replicas
   * @return replicas
  **/
  @Schema(description = "replicas")
  public Integer getReplicas() {
    return replicas;
  }

  public void setReplicas(Integer replicas) {
    this.replicas = replicas;
  }

  public UpdateEnvironmentServiceScalingDetailDTO requestsCpu(String requestsCpu) {
    this.requestsCpu = requestsCpu;
    return this;
  }

   /**
   * requestsCpu
   * @return requestsCpu
  **/
  @Schema(description = "requestsCpu")
  public String getRequestsCpu() {
    return requestsCpu;
  }

  public void setRequestsCpu(String requestsCpu) {
    this.requestsCpu = requestsCpu;
  }

  public UpdateEnvironmentServiceScalingDetailDTO noLimitsCpu(Boolean noLimitsCpu) {
    this.noLimitsCpu = noLimitsCpu;
    return this;
  }

   /**
   * noLimitsCpu
   * @return noLimitsCpu
  **/
  @Schema(description = "noLimitsCpu")
  public Boolean isNoLimitsCpu() {
    return noLimitsCpu;
  }

  public void setNoLimitsCpu(Boolean noLimitsCpu) {
    this.noLimitsCpu = noLimitsCpu;
  }

  public UpdateEnvironmentServiceScalingDetailDTO requestsMemory(String requestsMemory) {
    this.requestsMemory = requestsMemory;
    return this;
  }

   /**
   * requestsMemory
   * @return requestsMemory
  **/
  @Schema(description = "requestsMemory")
  public String getRequestsMemory() {
    return requestsMemory;
  }

  public void setRequestsMemory(String requestsMemory) {
    this.requestsMemory = requestsMemory;
  }

  public UpdateEnvironmentServiceScalingDetailDTO memoryScaleFactor(BigDecimal memoryScaleFactor) {
    this.memoryScaleFactor = memoryScaleFactor;
    return this;
  }

   /**
   * memoryScaleFactor
   * minimum: 1
   * maximum: 2
   * @return memoryScaleFactor
  **/
  @Schema(description = "memoryScaleFactor")
  public BigDecimal getMemoryScaleFactor() {
    return memoryScaleFactor;
  }

  public void setMemoryScaleFactor(BigDecimal memoryScaleFactor) {
    this.memoryScaleFactor = memoryScaleFactor;
  }

  public UpdateEnvironmentServiceScalingDetailDTO storageSize(String storageSize) {
    this.storageSize = storageSize;
    return this;
  }

   /**
   * storageSize
   * @return storageSize
  **/
  @Schema(description = "storageSize")
  public String getStorageSize() {
    return storageSize;
  }

  public void setStorageSize(String storageSize) {
    this.storageSize = storageSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateEnvironmentServiceScalingDetailDTO updateEnvironmentServiceScalingDetailDTO = (UpdateEnvironmentServiceScalingDetailDTO) o;
    return Objects.equals(this.code, updateEnvironmentServiceScalingDetailDTO.code) &&
        Objects.equals(this.replicas, updateEnvironmentServiceScalingDetailDTO.replicas) &&
        Objects.equals(this.requestsCpu, updateEnvironmentServiceScalingDetailDTO.requestsCpu) &&
        Objects.equals(this.noLimitsCpu, updateEnvironmentServiceScalingDetailDTO.noLimitsCpu) &&
        Objects.equals(this.requestsMemory, updateEnvironmentServiceScalingDetailDTO.requestsMemory) &&
        Objects.equals(this.memoryScaleFactor, updateEnvironmentServiceScalingDetailDTO.memoryScaleFactor) &&
        Objects.equals(this.storageSize, updateEnvironmentServiceScalingDetailDTO.storageSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, replicas, requestsCpu, noLimitsCpu, requestsMemory, memoryScaleFactor, storageSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateEnvironmentServiceScalingDetailDTO {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    replicas: ").append(toIndentedString(replicas)).append("\n");
    sb.append("    requestsCpu: ").append(toIndentedString(requestsCpu)).append("\n");
    sb.append("    noLimitsCpu: ").append(toIndentedString(noLimitsCpu)).append("\n");
    sb.append("    requestsMemory: ").append(toIndentedString(requestsMemory)).append("\n");
    sb.append("    memoryScaleFactor: ").append(toIndentedString(memoryScaleFactor)).append("\n");
    sb.append("    storageSize: ").append(toIndentedString(storageSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
