/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Update the BillingConfiguration of given Environment
 */
@Schema(description = "Update the BillingConfiguration of given Environment")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class UpdateEnvironmentBillingConfigurationDTO {
  @SerializedName("sapProductNumber")
  private String sapProductNumber = null;

  @SerializedName("crmTenantId")
  private String crmTenantId = null;

  public UpdateEnvironmentBillingConfigurationDTO sapProductNumber(String sapProductNumber) {
    this.sapProductNumber = sapProductNumber;
    return this;
  }

   /**
   * SAP Product Number
   * @return sapProductNumber
  **/
  @Schema(required = true, description = "SAP Product Number")
  public String getSapProductNumber() {
    return sapProductNumber;
  }

  public void setSapProductNumber(String sapProductNumber) {
    this.sapProductNumber = sapProductNumber;
  }

  public UpdateEnvironmentBillingConfigurationDTO crmTenantId(String crmTenantId) {
    this.crmTenantId = crmTenantId;
    return this;
  }

   /**
   * SAP CRM tenant ID
   * @return crmTenantId
  **/
  @Schema(required = true, description = "SAP CRM tenant ID")
  public String getCrmTenantId() {
    return crmTenantId;
  }

  public void setCrmTenantId(String crmTenantId) {
    this.crmTenantId = crmTenantId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateEnvironmentBillingConfigurationDTO updateEnvironmentBillingConfigurationDTO = (UpdateEnvironmentBillingConfigurationDTO) o;
    return Objects.equals(this.sapProductNumber, updateEnvironmentBillingConfigurationDTO.sapProductNumber) &&
        Objects.equals(this.crmTenantId, updateEnvironmentBillingConfigurationDTO.crmTenantId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sapProductNumber, crmTenantId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateEnvironmentBillingConfigurationDTO {\n");
    
    sb.append("    sapProductNumber: ").append(toIndentedString(sapProductNumber)).append("\n");
    sb.append("    crmTenantId: ").append(toIndentedString(crmTenantId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
