/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.cx.commercecloud.management.openapi.model.EnvironmentDatabaseSchemaPerformanceDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Database scaling update
 */
@Schema(description = "Database scaling update")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class UpdateEnvironmentDatabaseSchemaScalingDetailDTO {
  @SerializedName("code")
  private String code = null;

  @SerializedName("maxSizeInMb")
  private Long maxSizeInMb = null;

  @SerializedName("haReplicaCount")
  private Integer haReplicaCount = null;

  @SerializedName("performance")
  private EnvironmentDatabaseSchemaPerformanceDTO performance = null;

  public UpdateEnvironmentDatabaseSchemaScalingDetailDTO code(String code) {
    this.code = code;
    return this;
  }

   /**
   * code
   * @return code
  **/
  @Schema(required = true, description = "code")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public UpdateEnvironmentDatabaseSchemaScalingDetailDTO maxSizeInMb(Long maxSizeInMb) {
    this.maxSizeInMb = maxSizeInMb;
    return this;
  }

   /**
   * maxSizeInMb
   * @return maxSizeInMb
  **/
  @Schema(description = "maxSizeInMb")
  public Long getMaxSizeInMb() {
    return maxSizeInMb;
  }

  public void setMaxSizeInMb(Long maxSizeInMb) {
    this.maxSizeInMb = maxSizeInMb;
  }

  public UpdateEnvironmentDatabaseSchemaScalingDetailDTO haReplicaCount(Integer haReplicaCount) {
    this.haReplicaCount = haReplicaCount;
    return this;
  }

   /**
   * haReplicaCount
   * @return haReplicaCount
  **/
  @Schema(description = "haReplicaCount")
  public Integer getHaReplicaCount() {
    return haReplicaCount;
  }

  public void setHaReplicaCount(Integer haReplicaCount) {
    this.haReplicaCount = haReplicaCount;
  }

  public UpdateEnvironmentDatabaseSchemaScalingDetailDTO performance(EnvironmentDatabaseSchemaPerformanceDTO performance) {
    this.performance = performance;
    return this;
  }

   /**
   * Get performance
   * @return performance
  **/
  @Schema(description = "")
  public EnvironmentDatabaseSchemaPerformanceDTO getPerformance() {
    return performance;
  }

  public void setPerformance(EnvironmentDatabaseSchemaPerformanceDTO performance) {
    this.performance = performance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateEnvironmentDatabaseSchemaScalingDetailDTO updateEnvironmentDatabaseSchemaScalingDetailDTO = (UpdateEnvironmentDatabaseSchemaScalingDetailDTO) o;
    return Objects.equals(this.code, updateEnvironmentDatabaseSchemaScalingDetailDTO.code) &&
        Objects.equals(this.maxSizeInMb, updateEnvironmentDatabaseSchemaScalingDetailDTO.maxSizeInMb) &&
        Objects.equals(this.haReplicaCount, updateEnvironmentDatabaseSchemaScalingDetailDTO.haReplicaCount) &&
        Objects.equals(this.performance, updateEnvironmentDatabaseSchemaScalingDetailDTO.performance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, maxSizeInMb, haReplicaCount, performance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateEnvironmentDatabaseSchemaScalingDetailDTO {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    maxSizeInMb: ").append(toIndentedString(maxSizeInMb)).append("\n");
    sb.append("    haReplicaCount: ").append(toIndentedString(haReplicaCount)).append("\n");
    sb.append("    performance: ").append(toIndentedString(performance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
