/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * Update scheduled activity request
 */
@Schema(description = "Update scheduled activity request")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class UpdateScheduledActivityRequestDTO {
  @SerializedName("scheduledTimestamp")
  private OffsetDateTime scheduledTimestamp = null;

  public UpdateScheduledActivityRequestDTO scheduledTimestamp(OffsetDateTime scheduledTimestamp) {
    this.scheduledTimestamp = scheduledTimestamp;
    return this;
  }

   /**
   * Time the activity is scheduled for
   * @return scheduledTimestamp
  **/
  @Schema(required = true, description = "Time the activity is scheduled for")
  public OffsetDateTime getScheduledTimestamp() {
    return scheduledTimestamp;
  }

  public void setScheduledTimestamp(OffsetDateTime scheduledTimestamp) {
    this.scheduledTimestamp = scheduledTimestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateScheduledActivityRequestDTO updateScheduledActivityRequestDTO = (UpdateScheduledActivityRequestDTO) o;
    return Objects.equals(this.scheduledTimestamp, updateScheduledActivityRequestDTO.scheduledTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scheduledTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateScheduledActivityRequestDTO {\n");
    
    sb.append("    scheduledTimestamp: ").append(toIndentedString(scheduledTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
