/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.cx.commercecloud.management.openapi.model.UpdateEnvironmentDatabaseSchemaScalingDetailDTO;
import com.sap.cx.commercecloud.management.openapi.model.UpdateEnvironmentKubernetesClusterScalingDetailDTO;
import com.sap.cx.commercecloud.management.openapi.model.UpdateEnvironmentServiceScalingDetailDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Environment scaling update
 */
@Schema(description = "Environment scaling update")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class UpdateEnvironmentScalingDetailRequestDTO {
  @SerializedName("kubernetesClusters")
  private List<UpdateEnvironmentKubernetesClusterScalingDetailDTO> kubernetesClusters = null;

  @SerializedName("databaseSchemas")
  private List<UpdateEnvironmentDatabaseSchemaScalingDetailDTO> databaseSchemas = null;

  @SerializedName("services")
  private List<UpdateEnvironmentServiceScalingDetailDTO> services = null;

  public UpdateEnvironmentScalingDetailRequestDTO kubernetesClusters(List<UpdateEnvironmentKubernetesClusterScalingDetailDTO> kubernetesClusters) {
    this.kubernetesClusters = kubernetesClusters;
    return this;
  }

  public UpdateEnvironmentScalingDetailRequestDTO addKubernetesClustersItem(UpdateEnvironmentKubernetesClusterScalingDetailDTO kubernetesClustersItem) {
    if (this.kubernetesClusters == null) {
      this.kubernetesClusters = new ArrayList<UpdateEnvironmentKubernetesClusterScalingDetailDTO>();
    }
    this.kubernetesClusters.add(kubernetesClustersItem);
    return this;
  }

   /**
   * kubernetesClusters
   * @return kubernetesClusters
  **/
  @Schema(description = "kubernetesClusters")
  public List<UpdateEnvironmentKubernetesClusterScalingDetailDTO> getKubernetesClusters() {
    return kubernetesClusters;
  }

  public void setKubernetesClusters(List<UpdateEnvironmentKubernetesClusterScalingDetailDTO> kubernetesClusters) {
    this.kubernetesClusters = kubernetesClusters;
  }

  public UpdateEnvironmentScalingDetailRequestDTO databaseSchemas(List<UpdateEnvironmentDatabaseSchemaScalingDetailDTO> databaseSchemas) {
    this.databaseSchemas = databaseSchemas;
    return this;
  }

  public UpdateEnvironmentScalingDetailRequestDTO addDatabaseSchemasItem(UpdateEnvironmentDatabaseSchemaScalingDetailDTO databaseSchemasItem) {
    if (this.databaseSchemas == null) {
      this.databaseSchemas = new ArrayList<UpdateEnvironmentDatabaseSchemaScalingDetailDTO>();
    }
    this.databaseSchemas.add(databaseSchemasItem);
    return this;
  }

   /**
   * databaseSchemas
   * @return databaseSchemas
  **/
  @Schema(description = "databaseSchemas")
  public List<UpdateEnvironmentDatabaseSchemaScalingDetailDTO> getDatabaseSchemas() {
    return databaseSchemas;
  }

  public void setDatabaseSchemas(List<UpdateEnvironmentDatabaseSchemaScalingDetailDTO> databaseSchemas) {
    this.databaseSchemas = databaseSchemas;
  }

  public UpdateEnvironmentScalingDetailRequestDTO services(List<UpdateEnvironmentServiceScalingDetailDTO> services) {
    this.services = services;
    return this;
  }

  public UpdateEnvironmentScalingDetailRequestDTO addServicesItem(UpdateEnvironmentServiceScalingDetailDTO servicesItem) {
    if (this.services == null) {
      this.services = new ArrayList<UpdateEnvironmentServiceScalingDetailDTO>();
    }
    this.services.add(servicesItem);
    return this;
  }

   /**
   * services
   * @return services
  **/
  @Schema(description = "services")
  public List<UpdateEnvironmentServiceScalingDetailDTO> getServices() {
    return services;
  }

  public void setServices(List<UpdateEnvironmentServiceScalingDetailDTO> services) {
    this.services = services;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateEnvironmentScalingDetailRequestDTO updateEnvironmentScalingDetailRequestDTO = (UpdateEnvironmentScalingDetailRequestDTO) o;
    return Objects.equals(this.kubernetesClusters, updateEnvironmentScalingDetailRequestDTO.kubernetesClusters) &&
        Objects.equals(this.databaseSchemas, updateEnvironmentScalingDetailRequestDTO.databaseSchemas) &&
        Objects.equals(this.services, updateEnvironmentScalingDetailRequestDTO.services);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kubernetesClusters, databaseSchemas, services);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateEnvironmentScalingDetailRequestDTO {\n");
    
    sb.append("    kubernetesClusters: ").append(toIndentedString(kubernetesClusters)).append("\n");
    sb.append("    databaseSchemas: ").append(toIndentedString(databaseSchemas)).append("\n");
    sb.append("    services: ").append(toIndentedString(services)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
