/*
 * SAP Commerce Cloud - Management API
 * The API to manage your SAP Commerce environments in the cloud, including provisioning, building releases, deploying, operating and more.
 *
 * OpenAPI spec version: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.cx.commercecloud.management.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.cx.commercecloud.management.openapi.model.UserRoleAssignmentDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * List of user role assignments
 */
@Schema(description = "List of user role assignments")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-04T11:10:37.768860+02:00[Europe/Rome]")

public class UserRoleAssignmentListDTO {
  @SerializedName("items")
  private List<UserRoleAssignmentDTO> items = new ArrayList<UserRoleAssignmentDTO>();

  public UserRoleAssignmentListDTO items(List<UserRoleAssignmentDTO> items) {
    this.items = items;
    return this;
  }

  public UserRoleAssignmentListDTO addItemsItem(UserRoleAssignmentDTO itemsItem) {
    this.items.add(itemsItem);
    return this;
  }

   /**
   * UserRoleAssignmentDTO list
   * @return items
  **/
  @Schema(required = true, description = "UserRoleAssignmentDTO list")
  public List<UserRoleAssignmentDTO> getItems() {
    return items;
  }

  public void setItems(List<UserRoleAssignmentDTO> items) {
    this.items = items;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserRoleAssignmentListDTO userRoleAssignmentListDTO = (UserRoleAssignmentListDTO) o;
    return Objects.equals(this.items, userRoleAssignmentListDTO.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(items);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserRoleAssignmentListDTO {\n");
    
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
