# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:

    branches: '*'
    tags: '*'
  pull_request:
    branches: [ "main" ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Setup Gluon's GraalVM
      uses: gluonhq/setup-graalvm@master
      with:
        jdk: 'java17'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install libraries
      run: |
        sudo apt update
        sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle Wrapper
      run: ./gradlew clean build

    - name: Gluon build
      run: ./gradlew nativeBuild

    - uses: actions/upload-artifact@v4
      with:
        name: linux
        if-no-files-found: error
        path: build/gluonfx/x86_64-linux/sap-commerce-cloud-management-api-gui

  build-osx:
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Setup Gluon's GraalVM
      uses: gluonhq/setup-graalvm@master
      with:
        jdk: 'java17'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle Wrapper
      run: ./gradlew clean build

    - name: Gluon build
      run: ./gradlew nativeBuild

    - name: Gluon package
      run: ./gradlew nativePackage --stacktrace

    - uses: actions/upload-artifact@v4
      with:
        name: mac
        if-no-files-found: error
        path: build/gluonfx/x86_64-darwin/sap-commerce-cloud-management-api-gui*

  build-windows:
    if: false
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Visual Studio shell
      uses: egor-tensin/vs-shell@v1

    - uses: actions/checkout@v4
    - name: Setup Gluon's GraalVM
      uses: gluonhq/setup-graalvm@master
      with:
        jdk: 'java17'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle Wrapper
      run: .\gradlew.bat clean build

    - name: Gluon build
      run: .\gradlew.bat nativeBuild

    - name: Gluon package
      run: .\gradlew.bat nativePackage --stacktrace

    - uses: actions/upload-artifact@v4
      with:
        name: windows
        if-no-files-found: error
        path: build/gluonfx/x86_64-darwin/sap-commerce-cloud-management-api-gui*
